### ISSUE TITLE
Registering .IT issue

### ISSUE THREAD

**Issue by elbutanero** [openprovider/OP-WHMCS7#1]
We found a small problem registering .IT domains, seems that the plugin pass to the registrar more data than expected. 
In our specific case, because in Italy for individual is compulsory the "codice fiscale" (like the BSN in Nederland or Social Security Number in other countries), but not other data, if the plugin is passing by the Passport Number, the Registrar do not permit to the user to complete the registration, complaining about missing data.
So in the code (in openprovider.php from row 156):

   ```
      if($fields['ownerType'] == 'Individual')
            {
                $additionalData->set('socialSecurityNumber', $fields['socialSecurityNumber']);
		$additionalData->set('passportNumber', $fields['passportNumber']); 
                
            } elseif($fields['ownerType'] == 'Company')
            {
                $additionalData->set('companyRegistrationNumber', $fields['companyRegistrationNumber']);
                $additionalData->set('VATNumber', $fields['VATNumber']);
	   }
```

We simply add a check if we are registering a .IT and exclude the "passportNumber" parameter. 
Also, even if it's not depending directly from the plugin, but from the user behavior, when the user doesn't specify "Individual", but leave "Company" (in alphabetical order in the dropdown is the first option) even if he don't specify a VAT number, seems that the plugin, in that code, consider the request as a Company, so the first part of the IF clause is false and trying to add **VATNumber** and **companyRegistrationNumber** that in that case are probably empty fields, instead of the **socialSecurityNumber** really needed in this case.

We found a workaround, adding the **socialSecurityNumber** also in the company part of the IF clause, in case of .IT tld.
It's not elegant, we know, but seems it's working. 

So here is the modified part:

```
         if($fields['ownerType'] == 'Individual')
            {
                $additionalData->set('socialSecurityNumber', $fields['socialSecurityNumber']);
				 
				if($params['tld'] != 'it')
				{
					$additionalData->set('passportNumber', $fields['passportNumber']);
				}
                
            } elseif($fields['ownerType'] == 'Company')
            {
                $additionalData->set('companyRegistrationNumber', $fields['companyRegistrationNumber']);
                $additionalData->set('VATNumber', $fields['VATNumber']);
								
		if($params['tld'] == 'it')
		{
			$additionalData->set('socialSecurityNumber', $fields['socialSecurityNumber']);
		}
				
            }
```

Probably there's a better way to achieve the result, let us know.

**Comment by wmetge** [comment]
elbutanero, thanks for sharing your solution here! We may include it in the next release.

**Comment by DamageESP** [comment]
Something similar happens with `.es` domains and probably with other localized domains as well.

Going to try the code @elbutanero provided and adapt it if necessary. It would be nice if this issue could be given some thought and get fixed. I'm sure a lot of people are not using OpenProvider because of these kinds of errors.

Thanks again @elbutanero.

**Comment by wmetge** [comment]
Hi @DamageESP and @elbutanero, thank you for your feedback and cooperation.

note that the latest version of the module has a function for automatically displaying fields for collecting additional domain and customer data on the WHMCS checkout page. The readme describes how to create the correct file in "<WHMCS root>/resources/domains"
