### ISSUE TITLE
[BUG] Many error logs in tblerrorlog

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#101]
**Describe the bug**
Thousands of records are being entered into the database table: tblerrorlog

count(): Parameter must be an array or an object that implements Countable
modules/registrars/openprovider/OpenProvider/API/APITools.php

**To Reproduce**
See mysql table. Image: https://i.gyazo.com/fc5bf38b21e1db1ac6124073234be7f3.png

It creates so many that it blocks my WHMCS in each cron run, due to having to consult thousands of records.

**Screenshots**
https://i.gyazo.com/fc5bf38b21e1db1ac6124073234be7f3.png

**Server info:**
 - Distro: Centos 7
 - PHP: 7.3
 - WHMCS 8.0.1

**Comment by wmetge** [comment]
@coriaweb Thank you for letting us know, we are looking into the issue.

**Comment by soberoctober** [comment]
@coriaweb have you noticed any patterns that cause this error to appear? any specific action that you do from WHMCS?

**Comment by coriaweb** [comment]
Hi! I really don't know. I just saw that I was having problems with the crons and checking I got to that table in the database, which had over half a million records.

It is true that with the new updates of WHMCS this has improved, now I only have about 10,000. But even so, your records keep appearing, look:

https://i.gyazo.com/62680872214b560a8a294fbbede6f2a7.png
