### ISSUE TITLE
tblDomainSyncOpenprovider table missing

### ISSUE THREAD

**Issue by romaict** [openprovider/OP-WHMCS7#102]
I started a new installation of whmcs and installed the Openprovider Module. After connecting to openprovider i can see a sync status with balance and the ammount of domain names. but when i sync them with the cron job, i get the error that tblDomainSyncOpenprovider doesn't exist. If i check the database this table isn't there. Can i manually add this table and which fields do i need to create? or is there a sql script to create this table

**Comment by soberoctober** [comment]
@romaict thanks for reporting the issue. We'll investigate why the table is not created when it doesn't exist.

Meanwhile, as a workaround you can create it using this statement:
```
CREATE TABLE `tblDomainSyncOpenprovider` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `last_sync` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=96 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

**Comment by romaict** [comment]
Thanks for this update. I think it was because i installed WHMCS 8 and not 7. After reinstalling 7 and the modules the table was created. Only existing domains do not appear in WHMCS. I ran all the cron jobs, i can see the Openprovider widget with balance and amount of domains on the home page, but they do not synchronise.

**Comment by soberoctober** [comment]
@romaict domains that were not created via the module will not be added by the sync script.
If you have a number of domains that you created via RCP or API, they need to be [imported manually](https://support.openprovider.eu/hc/en-us/articles/360037011194-How-to-import-domains-to-WHMCS-manually).
