### ISSUE TITLE
[BUG] Domain registration not possible in WHMCS 8.02

### ISSUE THREAD

**Issue by telehost** [openprovider/OP-WHMCS7#105]
New domains can not be registrated in WHMCS 8.02 (blank and new installation of WHMCS)

Already reported to your support 1 week ago.

See error
![Ashampoo_Snap_Samstag, 17  Oktober 2020_16h42m30s_007_WHMCS - Register-Transfer Domain - Mozilla Firefox](https://user-images.githubusercontent.com/16341886/96341267-578f9380-1099-11eb-9840-9c000fe0aa27.png)

**Comment by wmetge** [comment]
@telehost thank you for contacting us. We're investigating the issue, but in the meantime you can manually create the table with :

```
CREATE TABLE `wHandles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `registrar` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `handle` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `data` text COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

**Comment by telehost** [comment]
you forgot `;`

**Comment by telehost** [comment]
anyway - there exists no tables from your module either ...

![ZDC_Snap_Montag, 19  Oktober 2020_19h22m44s_015_-nibCCapture--19807223-A348-4984-9F6B-109A76477CB2-](https://user-images.githubusercontent.com/16341886/96490585-526d4880-1241-11eb-92d7-366d00ff20e9.png)

So waiting to use your API since two weeks for now ...

**Comment by soberoctober** [comment]
Hi @telehost 

Sorry for the inconvenience.
Please use this statement to create wDomain_handle table:

```
wDomain_handle | CREATE TABLE `wDomain_handle` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `domain_id` int(10) unsigned NOT NULL,
  `handle_id` int(10) unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `wdomain_handle_handle_id_foreign` (`handle_id`),
  CONSTRAINT `wdomain_handle_handle_id_foreign` FOREIGN KEY (`handle_id`) REFERENCES `wHandles` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1178 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

**Comment by telehost** [comment]
Ah :-) - now it's working. I searched all files for the SQL statement to create tables, but nothing found ... maybe this is the problem.

Thank you - happy to be able to sell domains to waiting customers ...

![ZDC_Snap_Montag, 19  Oktober 2020_19h57m34s_021_WHMCS - Register-Transfer Domain - Mozilla Firefox](https://user-images.githubusercontent.com/16341886/96493836-c4e02780-1245-11eb-8f22-0fe353fe5e07.png)

**Comment by bipulbd08** [comment]
> @telehost thank you for contacting us. We're investigating the issue, but in the meantime you can manually create the table with :
> 
> ```
> CREATE TABLE `wHandles` (
>   `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
>   `user_id` int(10) unsigned NOT NULL,
>   `registrar` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
>   `type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
>   `handle` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
>   `data` text COLLATE utf8_unicode_ci NOT NULL,
>   `created_at` timestamp NULL DEFAULT NULL,
>   `updated_at` timestamp NULL DEFAULT NULL,
>   PRIMARY KEY (`id`)
> ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

Semicolon ";"  statement missing end of the comment.
