### ISSUE TITLE
[BUG] WHMCS Cronjob does not finish correctly ("Class 'OpenProvider\WhmcsRegistrar\Controllers\System\Carbon' not found")

### ISSUE THREAD

**Issue by jvkranenburg** [openprovider/OP-WHMCS7#107]
**Describe the bug**
Cronjob does not finish correctly in step 32/33.

**To Reproduce**
Run cronjob commandline:
/usr/bin/php -q /home/domain.com/public_html/cronsFiles/cron.php -F -vvv

WHMCS Automation Task Utility: all
==================================

 Daily Cron Automation Mode

Queuing Tasks
-------------

 Force run any tasks: ignore "in progress" and "is due"
 Task queues ready

Executing Application Queue
---------------------------

  0/33 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%  1 sec/1 sec  30.0 MiB 
 Currency Exchange Rates
  1/33 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   3%  1 sec/1 sec  30.0 MiB 
 Product Pricing Updates
  2/33 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   6%  1 sec/1 sec  30.0 MiB 
 Tenant Usage Metrics
  3/33 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]   9% 2 mins/20 mins 38.5 MiB 
 Invoices
  4/33 [▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░]  12% 2 mins/15 mins 40.5 MiB 
 Late Fees
  5/33 [▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░]  15% 2 mins/12 mins 40.5 MiB 
 Credit Card Charges
  6/33 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  18% 2 mins/10 mins 40.5 MiB 
 Invoice & Overdue Reminders
  7/33 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  21% 2 mins/9 mins 58.5 MiB 
 Domain Renewal Notices
  8/33 [▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░]  24% 2 mins/8 mins 58.5 MiB 
 Cancellation Requests
  9/33 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]  27% 2 mins/7 mins 58.5 MiB 
 Overdue Suspensions
 10/33 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  30% 2 mins/7 mins 58.5 MiB 
 Overdue Terminations
 11/33 [▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░]  33% 2 mins/6 mins 58.5 MiB 
 Fixed Term Terminations
 12/33 [▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░]  36% 2 mins/6 mins 58.5 MiB 
 Inactive Tickets
 13/33 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  39% 2 mins/5 mins 58.5 MiB 
 Prune Ticket Attachments
 14/33 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  42% 2 mins/5 mins 58.5 MiB 
 Delayed Affiliate Commissions
 15/33 [▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░]  45% 2 mins/5 mins 58.5 MiB 
 Affiliate Reports
 16/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░]  48% 2 mins/4 mins 58.5 MiB 
 Process Email Campaigns
 17/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  51% 2 mins/4 mins 58.5 MiB 
 Process Email Queue
 18/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░]  54% 2 mins/4 mins 58.5 MiB 
 Email Marketer Rules
 19/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░]  57% 2 mins/4 mins 58.5 MiB 
 SSL Sync
 20/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░]  60% 3 mins/4 mins 60.5 MiB 
 Credit Card Expiry Notices
 21/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░]  63% 3 mins/4 mins 60.5 MiB 
 Server Usage Stats
 22/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░]  66% 3 mins/4 mins 60.5 MiB 
 Overage Billing Charges
 23/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░]  69% 3 mins/4 mins 60.5 MiB 
 Client Status Update
 24/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░]  72% 3 mins/4 mins 60.5 MiB 
 Domain Expiry
 25/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░]  75% 3 mins/4 mins 60.5 MiB 
 Ticket Escalation Rules
 26/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░]  78% 3 mins/4 mins 60.5 MiB 
 Data Retention Pruning
 27/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░]  81% 3 mins/3 mins 60.5 MiB 
 Update Server Usage
 28/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░]  84% 3 mins/3 mins 60.5 MiB 
 Update Server Meta Data
 29/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░]  87% 3 mins/3 mins 60.5 MiB 
 Run Jobs Queue
 30/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░]  90% 3 mins/3 mins 60.5 MiB 
 WHMCS Updates
 31/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░]  93% 3 mins/3 mins 66.5 MiB 
 Domain Transfer Status Synchronisation
 32/33 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░]  96% 3 mins/3 mins 68.5 MiB

[WHMCS Application] ERROR: Error: Class 'OpenProvider\WhmcsRegistrar\Controllers\System\Carbon' not found in /home/domain.com/public_html/modules/registrars/openprovider/Controllers/System/TransferSyncController.php:77 Stack trace: #0 /home/domain.com/public_html/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Instance.php(47): OpenProvider\WhmcsRegistrar\Controllers\System\TransferSyncController->sync(Array) #1 /home/domain.com/public_html/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Launch.php(54): WeDevelopCoffee\wPower\Core\Instance->execute('sync', Array) #2 /home/domain.com/public_html/modules/registrars/openprovider/openprovider.php(270): WeDevelopCoffee\wPower\Core\Launch->output(Array, 'transferSync') #3 [internal function]: openprovider_TransferSync(Array) #4 /home/domain.com/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Task/DomainTransferSync.php(0): call_user_func('openprovider_Tr...', Array) #5 /home/domain.com/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Cron\Task\DomainTransferSync->__invoke() #6 /home/domain.com/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute() #7 /home/domain.com/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run() #8 /home/domain.com/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection(Object(WHMCS\Scheduling\Task\Collection)) #9 /home/domain.com/public_html/modules/servers/PleskExtended/vendor/symfony/console/Command/Command.php(259): WHMCS\Cron\Console\Command\AbstractCronCommand->execute(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #10 /home/domain.com/public_html/modules/servers/PleskExtended/vendor/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #11 /home/domain.com/public_html/modules/servers/PleskExtended/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(WHMCS\Cron\Console\Command\AllCommand), Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #12 /home/domain.com/public_html/modules/servers/PleskExtended/vendor/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #13 /home/domain.com/public_html/cronsFiles/cron.php(0): Symfony\Component\Console\Application->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #14 {main} {"exception":"[object] (Error(code: 0): Class 'OpenProvider\\WhmcsRegistrar\\Controllers\\System\\Carbon' not found at /home/domain.com/public_html/modules/registrars/openprovider/Controllers/System/TransferSyncController.php:77)"} []
Error: Class 'OpenProvider\WhmcsRegistrar\Controllers\System\Carbon' not found in /home/domain.com/public_html/modules/registrars/openprovider/Controllers/System/TransferSyncController.php:77

#0 /home/domain.com/public_html/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Instance.php(47): OpenProvider\WhmcsRegistrar\Controllers\System\TransferSyncController->sync(Array)
#1 /home/domain.com/public_html/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Launch.php(54): WeDevelopCoffee\wPower\Core\Instance->execute('sync', Array)
#2 /home/domain.com/public_html/modules/registrars/openprovider/openprovider.php(270): WeDevelopCoffee\wPower\Core\Launch->output(Array, 'transferSync')
#3 [internal function]: openprovider_TransferSync(Array)
#4 /home/domain.com/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Task/DomainTransferSync.php(0): call_user_func('openprovider_Tr...', Array)
#5 /home/domain.com/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Cron\Task\DomainTransferSync->__invoke()
#6 /home/domain.com/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute()
#7 /home/domain.com/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run()
#8 /home/domain.com/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection(Object(WHMCS\Scheduling\Task\Collection))
#9 /home/domain.com/public_html/modules/servers/PleskExtended/vendor/symfony/console/Command/Command.php(259): WHMCS\Cron\Console\Command\AbstractCronCommand->execute(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/domain.com/public_html/modules/servers/PleskExtended/vendor/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/domain.com/public_html/modules/servers/PleskExtended/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(WHMCS\Cron\Console\Command\AllCommand), Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/domain.com/public_html/modules/servers/PleskExtended/vendor/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/domain.com/public_html/cronsFiles/cron.php(0): Symfony\Component\Console\Application->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}

**Expected behavior**
Finish correctly until step 33

**Additional context**
WHMCS version 8.0.4 (but also in 8.0.3)
OP-WHMCS7 version 3.3.2 (Latest)

**Comment by stmc-droid** [comment]
Same issue with WHMCS Version: 7.9.2

**Comment by wmetge** [comment]
@stmc-droid @jvkranenburg , thank you for the feedback, we'll look into it

**Comment by willdashwood** [comment]
This is a repeat of #89

**Comment by lennarttd** [comment]
@wmetge Please merge my commit #106 of Oct 20 to the master branche. Reinitialized it already after it got removed again.

**Comment by soberoctober** [comment]
thanks @lennarttd, PR was merged.
