### ISSUE TITLE
Update and version info[FR]

### ISSUE THREAD

**Issue by chajadesign** [openprovider/OP-WHMCS7#109]
When accessing the module inside WHMCS there is no info displayed about the version.
Can you implement this so it is easier to check when to update? 
Or maybe you can implement an update message.

**Comment by wmetge** [comment]
Hi @chajadesign, thanks for the feedback. When you are looking at the configurations page, do you see the module version as pictured here: 

![Selection_416](https://user-images.githubusercontent.com/26813274/98684385-b2669300-2398-11eb-9020-aa30609959fa.png)

update messages will be implemented in the near future.

**Comment by chajadesign** [comment]
Yes that is correct, looking forward to the update message feature.
