### ISSUE TITLE
DNS Template not shown on configuration[BUG]

### ISSUE THREAD

**Issue by BenMeesters** [openprovider/OP-WHMCS7#110]
**Describe the bug**
DNS Template not shown on configuration template, so not able to select de template

**To Reproduce**
whmcs 8.0.4
openprovider whmcs7 version v3.4.1
new install

**Expected behavior**
select de template for registration domains

**Screenshots**

**Server info:**
 - Distro: debian 9
 - PHP: 7.4
 - Web server: apache 2.4

**Comment by soberoctober** [comment]
Hi @BenMeesters 

If the DNS template dropdown is not shown on the configuration page, most probably it means that the module could not authenticate within the API endpoint. 
Could you make sure that the module authenticates successfully in Logs > Module logs?

**Comment by BenMeesters** [comment]
Hi Nikolaj,

 

The module authenticates fine and the commands work from the user for the domain actions, but no option is presented for the DNS template.

Recent log output API history modify domain req from the openprovider site.

 

<?xml version="1.0" encoding="UTF-8"?> <openXML> <credentials> <username>DDhost</username> <password>...</password> <client>whmcs-3.4.1</client> <initiator>admin</initiator> </credentials> <modifyDomainRequest> <domain> <name>claimen-domein</name> <extension>nl</extension> </domain> <autorenew>default</autorenew> </modifyDomainRequest> </openXML>      <?xml version="1.0" encoding="UTF-8"?> <openXML> <reply> <code>0</code> <desc></desc> <data> <id>9327511</id> <status>ACT</status> </data> </reply> </openXML>

 

Without this working we cant upgrade to the latest version of WHMCS. What to do?

 

Met vriendelijke groet,

 

Ben Meesters


Van Schuppenstraat 5

5253DD Nieuwkuijk
T 073-8505242
 <mailto:ben.meesters@home.nl> ben.meesters@home.nl

 

Van: nikolaj zavalny <notifications@github.com> 
Verzonden: donderdag 14 januari 2021 09:19
Aan: openprovider/OP-WHMCS7 <OP-WHMCS7@noreply.github.com>
CC: BenMeesters <ben.meesters@home.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [openprovider/OP-WHMCS7] DNS Template not shown on configuration[BUG] (#110)

 

Hi @BenMeesters <https://github.com/BenMeesters> 

If the DNS template dropdown is not shown on the configuration page, most probably it means that the module could not authenticate within the API endpoint.
Could you make sure that the module authenticates successfully in Logs > Module logs?

**Comment by BenMeesters** [comment]
Please check your code. I reinstalled the plugin and I don't get an option to set the DNS template dropdown.

Otherwise, the plugin seems to work fine. That also proves that the credentials are correct and that it is an error in your code.

Hopefully you can fix this soon.

Regards, Ben

**Comment by wmetge** [comment]
@BenMeesters Thanks for bringing this to our attention. We had an error with the DNS template not appearing in some cases. 

In the latest version of the module (version 4+) we have simplified the GUI configurations and relocated advanced configuration options.
