### ISSUE TITLE
Domain lookup in WHMCS template [BUG]

### ISSUE THREAD

**Issue by chajadesign** [openprovider/OP-WHMCS7#111]
The domain lookup inside the default WHMCS template or third party template is not working.
It did not show any output or some error text: 'Domain names must start with a letter or number and must be between and characters long'.
I have contacted WHMCS and they resolved it by changing the lookup from openprovider to WHMCS Namespinning.

My installation is:
WHMCS 8.0.4
Openprovider module 3.3.2

Server setup:
CentOS 7 64-bit
PHP 7.3.25
Nginx

**Comment by soberoctober** [comment]
hi @chajadesign 

could you please try it out with the latest available version, which is 3.4.1?

**Comment by chajadesign** [comment]
Thank you, it is working now.
