### ISSUE TITLE
Wrong due date for product with free domain

### ISSUE THREAD

**Issue by wmmuhsin** [openprovider/OP-WHMCS7#113]
Hello,

We are using the WHMCS module and our domain due dates now expire 2 days later than expiry date. This is because openprovider has 2 expiry dates, namely: expiration date and expiration date openprovider? Which is leading?

We give domains for free with a web hosting product. In the module there is a possibility to automatically change the due date to x number of days earlier, but then we have the product that has a different date.

Do you have a solution for this?

**Comment by wmetge** [comment]
Hi @wmmuhsin ,

> ...openprovider has 2 expiry dates, namely: expiration date and expiration date openprovider? Which is leading?

The Openprovider due date is the date on which renewals are processed for the domain. This can vary between TLDs, but is generally two days before the expiration date at the registry. The Openprovider expiration date is the date which the module uses to calculate the expiration date in WHMCS.

> Do you have a solution for this?
Could you please explain the desired result?  You want the domain expiration date to match the renewal date of the hosting product?

**Comment by wmmuhsin** [comment]
> Hi @wmmuhsin ,
> 
> > ...openprovider has 2 expiry dates, namely: expiration date and expiration date openprovider? Which is leading?
> 
> The Openprovider due date is the date on which renewals are processed for the domain. This can vary between TLDs, but is generally two days before the expiration date at the registry. The Openprovider expiration date is the date which the module uses to calculate the expiration date in WHMCS.
> 
> > Do you have a solution for this?
> 
> Could you please explain the desired result? You want the domain expiration date to match the renewal date of the hosting product?

**Comment by wmmuhsin** [comment]
The question is:

We offer free domains with hosting product. In the module there is a possibility to automatically change the due date of a domain, but the product due date is then different. This is a big issue, because the domain will renewed earlier for free without payment.

**Comment by wmetge** [comment]
> We offer free domains with hosting product. In the module there is a possibility to automatically change the due date of a domain, but the product due date is then different. This is a big issue, because the domain will renewed earlier for free without payment.

1. In the Openprovider module, select the option to _use_ the WHMCS sync utility, and _not use_ the Openprovider cron sync. Once you've done this, all sync operations will be done by WHMCS, not by the module.

2. Turn off sync due date in WHMCS settings. In the link you've sent there is an explanation for how to do this: " for this reason we recommend disabling the Setup > General Settings > Domains tab > Sync Next Due Date option."

> Is it possible to change the product due date also with domain due date? Or do you have an another solution?

Specifically in answer to your question, it is possible to change due dates directly in the WHMCS database. If you're looking for a solution to this issue via configurations, please note that this deals with the internal logic of WHMCS, not the Openprovider module. WHMCS support may be able to assist you with this question
