### ISSUE TITLE
[BUG]cannot be resolved: Parameter $core of __construct()

### ISSUE THREAD

**Issue by itajooba** [openprovider/OP-WHMCS7#117]
**Describe the bug**
Fresh installation of plugin ended up with following error :   

DI\Definition\Exception\InvalidDefinition: Entry "WeDevelopCoffee\wPower\Core\Launch" cannot be resolved: Parameter $core of __construct() has no value defined or guessable
Full definition:
Object (
class = WeDevelopCoffee\wPower\Core\Launch
lazy = false
__construct(
$core = #UNDEFINED#
$router = #UNDEFINED#
$instance = #UNDEFINED#
$hooks = #UNDEFINED#
)
) in /home/domain/public_html/superclient/modules/addons/openprovider/vendor/php-di/php-di/src/Definition/Exception/InvalidDefinition.php:18
Stack trace:
#0 /home/domain/public_html/superclient/modules/addons/openprovider/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(156): DI\Definition\Exception\InvalidDefinition::create(Object(DI\Definition\ObjectDefinition), 'Entry "WeDevelo...')
#1 /home/domain/public_html/superclient/modules/addons/openprovider/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
#2 /home/domain/public_html/superclient/modules/addons/openprovider/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#3 /home/domain/public_html/superclient/modules/addons/openprovider/vendor/php-di/php-di/src/Container.php(387): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#4 /home/domain/public_html/superclient/modules/addons/openprovider/vendor/php-di/php-di/src/Container.php(138): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#5 /home/domain/public_html/superclient/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Core.php(60): DI\Container->get('WeDevelopCoffee...')
#6 /home/domain/public_html/superclient/modules/registrars/openprovider/init.php(14): WeDevelopCoffee\wPower\Core\Core->launch()
#7 /home/domain/public_html/superclient/modules/registrars/openprovider/openprovider.php(333): openprovider_registrar_launch('system')
#8 /home/domain/public_html/superclient/modules/registrars/openprovider/openprovider.php(43): openprovider_registrar_launch_decorator('config', Array)
#9 /home/domain/public_html/superclient/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): openprovider_getConfigArray(Array)
#10 /home/domain/public_html/superclient/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call('getConfigArray', Array)
#11 /home/domain/public_html/superclient/admin/configregistrars.php(0): WHMCS\Module\Registrar->call('getConfigArray')
#12 {main}

**To Reproduce**
after installtion 
Setup > Products/Services > Domain Registrars 

**Server info:**
 - WHMCS: 7.10.2
 - PHP: 7.0
 - Web server: ngix

**Additional context**

**Comment by wmetge** [comment]
@itajooba do you also experience this issue on WHMCS 8?

**Comment by itajooba** [comment]
We did not test it on WHMCS 8

**Comment by wmetge** [comment]
@itajooba are you able to upgrade your WHMCS version to 8+ ?
