### ISSUE TITLE
[BUG] Urgent error in the last update.

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#118]
**Describe the bug**
At checkout it shows error 500

**To Reproduce**
When the customer makes the payment it shows an error. The order arrives ok, but the customer shows an error.

**Additional context**

Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

For additional assistance, please reference the WHMCS TroubleShooting Guide »

ParseError: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/*******/modules/registrars/openprovider/Models/Tld.php:9
Stack trace:

**Comment by wmetge** [comment]
@coriaweb thanks for bringing this to our attention, we've made the fix
