### ISSUE TITLE
translation and menu item & ...

### ISSUE THREAD

**Issue by themshday** [openprovider/OP-WHMCS7#121]
3 issue here:

1st - menu item
----------------
Using 8.1 and DNSSEC section shows on domains that are not registered through DomainProvider and ends in below error once clicked:

`string(76) "The domain is not in your account; please transfer it to your account first."`

2nd - translation
-------------------
also translation is worst! so many files and no clue how to edit the "Menu Item" for DNSSEC Management.

Documentation and translation need more work to do for "clientareadomaindns.tpl" since it is fixed in 8.1 
Also "dnssec.php" & "dnssec.tpl" variables need to be in language file.

3rd - hardcoded path
-------------
also line 28 on dnssec.php has a path variable for site hardcoded as "/whmcs/" which cause the module to not work.

this issue is with CSS & JS files since /whmcs/ variable is also hardcoded to somewhere else I could not find, so CSS & JS files does not load too.

**Comment by wmetge** [comment]
@sorry4uboth thanks for the feedback! We'll roll out a fix as soon as possible
