### ISSUE TITLE
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'op_correctioninvoices' (SQL: alter table `tbldomains` add `op_correctioninvoices` double(10, 4) not null)

### ISSUE THREAD

**Issue by willdashwood** [openprovider/OP-WHMCS7#13]
When activating the OpenProvider domain addon, I got a 500 error and the addon failed to activate. When trying to activate again I get:

`SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'op_correctioninvoices' (SQL: alter table `tbldomains` add `op_correctioninvoices` double(10, 4) not null)`

Can the activation routine gracefully handle situations where it partially activated? I'm just trying to see what the original error was that caused it to fail during activation.

**Comment by wmetge** [comment]
Hi @willdashwood, thanks for bringing this to our attention. An exception has been added for this case, and has been included in the commits on October 1

**Comment by exhumept** [comment]
Hi,

I still got the same error using the new files(1st October) when trying activate the addon

Addon Module Activated
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'op_correctioninvoices' (SQL: alter table `tbldomains` add `op_correctioninvoices` double(10, 4) not null)
