### ISSUE TITLE
[BUG] The tags do not work.

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#131]
**Describe the bug**
Today, a customer who has a tag assigned to his profile, has registered a domain by creating a contact from within his profile to be in his customer's name.

When checking in openprovider, the new customer has been created without that tag.

It would be important that they register by assigning the tag.

**To Reproduce**
Register from the reseller account in WHMCS, but create a new contact for the domain to be registered in your customer's name.

**Comment by wmetge** [comment]
@coriaweb , thank you for the feedback. The linked commit solves the issue.
