### ISSUE TITLE
ID protection logic incorrect

### ISSUE THREAD

**Issue by willdashwood** [openprovider/OP-WHMCS7#15]
I've raised a support ticket (#412308) regarding this as it's a fairly important and urgent issue but probably appropriate to post this here too.

I believe the new WHMCS module is attempting to enable WHOIS privacy on domains that shouldn't have it enabled and vice versa. Having updated the module, I've noticed hundreds of domains with privacy enabled in our OP account that shouldn't have it enabled and domains that were previously protected that now aren't.

Having checked all the "OpenProvider Activity E-mail" notifications from overnight, I can see all the domains that have had the status toggled. I think this logic is incorrect in the new file modules/registrars/openprovider/Library/OpenProvider.php

```
	public function toggle_whois_protection($w_domain, \OpenProvider\API\Domain $domain, $opInfo)
	{
		// Check if we should auto renew or use the default settings
        // Note: the settings are in reverse since WHMCS updates the table after this hoo.
	    if($w_domain->idprotection == 0)
            $idprotection = 1; // OP sends the null value when no protection is set.
	    else
            $idprotection = '0';
```

Compared to the previously used  modules/registrars/openprovider/OpenProvider/OpenProvider.php

```
	public function toggle_whois_protection($domain, $opInfo)
	{
		// Check if we should auto renew or use the default settings
	    if($domain->idprotection == 0)
            $idprotection = null; // OP sends the null value when no protection is set.
	    else
            $idprotection = '1';
```

Furthermore I'm getting lots of notification emails with the subject "Error: action required before enabling Whois Privacy Protection". This error message is incorrect as we have already signed the contract and ID protection has been working fine. I think it's triggering an error because it's attempting to enable privacy on domains that shouldn't or even can't have it enabled. For example, expired domains or extensions that don't support it. The error handling needs to be a bit more thorough I think although fixing the above error should mean it doesn't get triggered so often in the first place.

**Comment by willdashwood** [comment]
Update: I see the above code actually hasn't changed since the previous release so it can't be that. This is a fairly important issue to highlight. We've been charged €424.50 in fees due to this error. Hopefully this can be fixed before others upgrade and have the same problem.

**Comment by wmetge** [comment]
Hi @willdashwood , thank you for bringing this to our attention. Our support department is working on your ticket, and a reasonable solution will be found for the fees accrued. 

The development team is working on a solution, and it will be uploaded as soon as it's available.

**Comment by willdashwood** [comment]
Thanks, yes the support team have been great.

I need to resolve this one way or another today. I could downgrade back to the older release which I still have a copy of. But I'd rather adjust the lines of code that are responsible for this error. Am I right in saying the following code should work?

```
	public function toggle_whois_protection($w_domain, \OpenProvider\API\Domain $domain, $opInfo)
	{
		// Check if we should auto renew or use the default settings
        // Note: the settings are in reverse since WHMCS updates the table after this hoo.
	    if($w_domain->idprotection == 0)
            $idprotection = 0; // OP sends the null value when no protection is set.
	    else
            $idprotection = '1';
```

**Comment by MrKoopie** [comment]
@willdashwood It looks like the equation was incorrect. This fix worked for me.

```
// Check if we should auto renew or use the default settings
 // Note: the settings are in reverse since WHMCS updates the table after this hoo.
if($w_domain->idprotection == 1)
            $idprotection = 1; // OP sends the null value when no protection is set.
else
            $idprotection = NULL;
```

**Comment by willdashwood** [comment]
Back from holiday. I see that modules/registrars/openprovider/Library/OpenProvider.php has now been updated. Have all issues been fixed and tested?

**Comment by wmetge** [comment]
Hi @willdashwood, yes, the issues surrounding incorrect syncing of WPP settings have been addressed with the commits on Oct 1
