### ISSUE TITLE
Disable domain contact verification for non TLD

### ISSUE THREAD

**Issue by BenMeesters** [openprovider/OP-WHMCS7#150]
Hi,

Were can i disable the trigger for domain contact verification? Now .nl domains are asked for verification bij ICANN.
Thats not okay as .nl is not a part of ICANN.

Thanks.

**Comment by wmetge** [comment]
hi @BenMeesters thanks for the feedback. We'll release a fix as soon as possible.

**Comment by BenMeesters** [comment]
Hi,

This is taking to long, plz provide info so i can disable this function.

**Comment by wmetge** [comment]
Hi @BenMeesters , please see the attached pull request which should solve the issue.
