### ISSUE TITLE
DNS Management Options

### ISSUE THREAD

**Issue by maverick85** [openprovider/OP-WHMCS7#151]
Hi,

After receiving an email announcing the new WHMCS module, we proceeded to update the module.
While reading through the documentation [Install the DNS management options](https://github.com/openprovider/OP-WHMCS7/blob/master/docs/custom_DNS_management_options.md) we read:

> Search for the version with the options like the one below. Note that it includes the "selected" substring:
> `<option value="A"{if $dnsrecord.type eq "A"} selected="selected"{/if}>A (Address)</option>`

This string no longer exists on WHMCS 8. It has been replaced with the following string:
`<option value="A"{if $dnsrecord.type eq "A"} selected="selected"{/if}>{lang key="domainDns.a"}</option>`

With specific focus to the part after the closing of the {/if}
Since this is out-of-date, I request confirmation about the strings to replace, since on the replacement part is wrong, I'm unsure if correcting the first <option> part on your provided string is enough.

Also I'd like to understand specifically what is the difference between the original string to find, with the new version, as shown on this screenshot:
<img width="801" alt="Screenshot 2021-03-12 at 18 13 26" src="https://user-images.githubusercontent.com/10200278/110981224-c29a7900-835e-11eb-9760-2cab9d2ff14e.png">

The step 2 asks to locate strings which are no longer there:
```
<option value="A">A (Address)</option>
<option value="AAAA">AAAA (Address)</option>
<option value="CAA">CAA</option>
<option value="CNAME">CNAME (Alias)</option>
<option value="MX">MX (Mail)</option>
<option value="SPF">SPF (spf, not recommended)</option>
<option value="SSHFP">SSHFP</option>
<option value="SRV">SRV</option>
<option value="TLSA">TLSA</option>
<option value="TXT">TXT (recommended for SPF)</option>
```

The current strings are:
```
<select name="dnsrecordtype[]" class="form-control">
  <option value="A">{lang key="domainDns.a"}</option>
  <option value="AAAA">{lang key="domainDns.aaaa"}</option>
  <option value="MXE">{lang key="domainDns.mxe"}</option>
  <option value="MX">{lang key="domainDns.mx"}</option>
  <option value="CNAME">{lang key="domainDns.cname"}</option>
  <option value="TXT">{lang key="domainDns.txt"}</option>
  <option value="URL">{lang key="domainDns.url"}</option>
  <option value="FRAME">{lang key="domainDns.frame"}</option>
</select>
```

About the MX record, is this string one of those where to add `or $dnsrecord.type eq "SRV"` ?
`<option value="MX"{if $dnsrecord.type eq "MX"} selected="selected"{/if}>{lang key="domainDns.mx"}</option>`

Thank you.

**Comment by wmetge** [comment]
@maverick85 , thanks for bringing this change to our attention. We will update the documentation accordingly. 

regarding your question:

> Also I'd like to understand specifically what is the difference between the original string to find, with the new version, as shown on this screenshot:

The values in the Openprovider documentation include DNS record types which are supported by Openprovider nameservers, but are not included by default in WHMCS. for example, CAA, SPF, SSHFP, SRV, TLSA, TXT. 

Unless you need to allow your customers to create such records via the client area, there's probably no need for you to modify the template file.

**Comment by maverick85** [comment]
Hi, I have been checking the documentation but I haven't seen any update regarding the mismatch between the records suggested and the records that are present on the template files.
When can be expected the documentation to be updated? thank you?

**Comment by wmetge** [comment]
We've updated the documentation with a more general explanation of how to add additional record types. 

You can find the DNS record types supported by Openprovider [in the KB](https://support.openprovider.eu/hc/en-us/articles/216648808-DNS-Records)

**Comment by maverick85** [comment]
Seen the new changes now. It looks much better now, cheers!
Thanks for the good work.

**Comment by wmetge** [comment]
Thank you for pointing out where we have room for improvement and for the follow up!

**Comment by maverick85** [comment]
Dear @wmetge, I would like to bring to your attention that the WHMCS team has made a follow up on the request for custom DNS management options/support for additional DNS records here:
https://requests.whmcs.com/topic/dependent-configurable-options#comment-22457

This comes as follow up of OpenProvider's request issued by OP here:
> WHMCS does not natively support all DNS records supported by Openprovider, so to add support for additional records, you will need to edit your template files. We have created a [request for WHMCS to make this easier. Please upvote this request here](https://requests.whmcs.com/topic/add-support-for-custom-dns-types).

https://github.com/openprovider/OP-WHMCS7/blob/master/docs/custom_DNS_management_options.md

**Comment by wmetge** [comment]
Dear @maverick85, could you help me understand the connection between [Dependent Configurable Options](https://requests.whmcs.com/topic/dependent-configurable-options#comment-22457) and [Add support for custom DNS types](https://requests.whmcs.com/topic/add-support-for-custom-dns-types) ?

**Comment by maverick85** [comment]
I'm removing my comment I mixed two different topics.
