### ISSUE TITLE
[FR] WHITELABEL NS RECORDS

### ISSUE THREAD

**Issue by maverick85** [openprovider/OP-WHMCS7#152]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the domains my clients register and want to manage through the DNS Manager have openprovider.nl instead of my domain name.

**Describe the solution you'd like**
Customer should be allowed to add CNAME records for the OpenProvider NS servers or A Records for OpenProvider IP's.
Upon successful validation those records would be used as authoritative name servers for the domains on the DNS Templates.
Having openprovider.nl as authoritative name servers isn't very... White Label.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by wmetge** [comment]
Hello @maverick85 ,

Thanks for the feedback. We will consider adding an out-of-the-box solution to this issue. In the meantime, as a workaround you can try the following:

1. Contact Openprovider support and request that they allow custom nameservers in your account
2. Set up your custom nameserver glue records to point to the Openprovider nameservers ip addresses. 
3. Set up a [custom template](https://support.openprovider.eu/hc/en-us/articles/216648688-How-to-use-DNS-templates) with the appropriate NS records
4. set your custom template name for the 'dnsTemplate' parameter in [advanced configurations ](https://github.com/openprovider/OP-WHMCS7/blob/master/docs/advanced_configurations.md)
5. edit the file `modules/registrars/openprovider/Controllers/Hooks/DnsNotificationController.php` with the following:

Change the "op_nameservers" array to your custom name server list:
so
```
    protected $op_nameservers = [
        'ns1.openprovider.nl',
        'ns2.openprovider.be',
        'ns3.openprovider.eu'
    ];
````
will be changed to:

```
    protected $op_nameservers = [
        '<your ns1>',
        '<your ns2>',
        '<etc.>'
    ];
```

and change the `error_message` variable on line 81 to something more appropriate.

**Comment by maverick85** [comment]
Hi @wmetge amazing reply. I am actually on a client this week so I won't have much time to look into it but I'll dive onto it as soon as I return to my office! Thanks a lot for the proposed solution, I'll probably send the email in the meanwhile. talk to you soon, have a good one!

**Comment by wmetge** [comment]
@maverick85 glad to help, please let us know if you run into any issues!

**Comment by wailer** [comment]
Any ETA for this feature to be released?

**Comment by wmetge** [comment]
Currently no ETA, but it is on our long-term roadmap

**Comment by wmmuhsin** [comment]
Hi,

Still not possible? When will this feature released?
