### ISSUE TITLE
[BUG] Problem with a region registering a .es domain

### ISSUE THREAD

**Issue by sperezf** [openprovider/OP-WHMCS7#154]
It is not possible to register a .es domain fif you are from the region of Álava, since the region field that appears in WHMCS is ARABA / ÁLAVA and the one that appears in openprovider is ALAVA

To reproduce the error, you simply have to try to register a .es domain with the ARABA / ÁLAVA region set in the WHCMS customer profile, then you will recieve an invalid state error.

**Comment by wmetge** [comment]
@sperezf Thank you for your feedback. Unfortunately the Spanish domain registry only accepts "ALAVA" as a valid region when registering a domain.

If you are expecting a large number of customers registering .es domains located in ARABA / ÁLAVA, you can change the value of the dropdown menu in your WHMCS instance:

in the file `<WHMCS root>/assets/js/StatesDropdown.js` You can find the array:

```
states['ES'] = ["ARABA/ÁLAVA","ALBACETE","ALICANTE","ALMERIA","AVILA","BADAJOZ","ILLES BALEARS","BARCELONA","BURGOS","CACERES","CADIZ","CASTELLON","CIUDAD REAL","CORDOBA","CORUÑA, A","CUENCA","GIRONA","GRANADA","GUADALAJARA","GIPUZKOA","HUELVA","HUESCA","JAEN","LEON","LLEIDA","RIOJA, LA","LUGO","MADRID","MALAGA","MURCIA","NAVARRA","OURENSE","ASTURIAS","PALENCIA","PALMAS, LAS","PONTEVEDRA","SALAMANCA","SANTA CRUZ DE TENERIFE","CANTABRIA","SEGOVIA","SEVILLA","SORIA","TARRAGONA","TERUEL","TOLEDO","VALENCIA","VALLADOLID","BIZKAIA","ZAMORA","ZARAGOZA","CEUTA","MELILLA","end"];
```
Here you can edit to "ARABA/ÁLAVA" to "ARABA"

You would also need to update contacts and tax information with the following commands in your database:

```
UPDATE `tblclients` SET `state`='ARABA' WHERE `state`='ARABA/ÁLAVA'
UPDATE `tblcontacts` SET `state`='ARABA' WHERE `state`='ARABA/ÁLAVA'
UPDATE `tblquotes` SET `state`='ARABA' WHERE `state`='ARABA/ÁLAVA'
UPDATE `tbltax` SET `state`='ARABA' WHERE `state`='ARABA/ÁLAVA'
```
