### ISSUE TITLE
[BUG] Tags error

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#159]
**Describe the bug**
Hello!

The tags seem to still not work.

A customer has registered the domain ID: 19123007

It seems that it still does not insert the label in the customer's file created in openprovider.

**Comment by wmetge** [comment]
Hi @coriaweb ,

Thanks for reaching out. We will take a look at it.

**Comment by coriaweb** [comment]
Have you been able to see something about this?

Greetings!

**Comment by wmetge** [comment]
Hi @coriaweb , is it correct that the contact was created before the tag management was introduced? We found an issue with the tag update button which wasn't updating all historical contacts, and a fix has been released. Please try the update button in the new version.

**Comment by coriaweb** [comment]
We just tested this. "I think" it already works correctly. When requesting the domain a client with an assigned tag, it is already assigned correctly.

**Comment by wmetge** [comment]
@coriaweb good to hear, please let us know if anything else comes up
