### ISSUE TITLE
SQLSTATE[42S21]

### ISSUE THREAD

**Issue by exhumept** [openprovider/OP-WHMCS7#16]
Hi,

I still got the same error using the newest files when trying activate the addon

Addon Module Activated
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'op_correctioninvoices' (SQL: alter table tbldomains add op_correctioninvoices double(10, 4) not null)

**Comment by wmetge** [comment]
@exhumept Thank you for bringing this to our attention, we'll post a fix within the week

**Comment by exhumept** [comment]
@wmetge thank you for reply.

This is what i get now using latest files:


Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

Error: Call to a member function getMessage() on null in /home/devmiztec/public_html/whmcs/modules/addons/openprovider/openprovider.php:83
Stack trace:
#0 /home/devmiztec/public_html/whmcs/admin/configaddonmods.php(0): openprovider_activate()
#1 {main}

**Comment by soberoctober** [comment]
@exhumept does this happen when you try registering a domain from the admin area?
for now, some operations are better be executed from client area while we're working on the fix.

**Comment by exhumept** [comment]
@soberoctober this error happen when i try to activate OpenProvider addon at menu Setup - Addon Modules - OpenProvider

**Comment by soberoctober** [comment]
@exhumept the add-on is an optional feature that is currently not stable enough for daily use.
if you can, please try to abstain from using it. it'll probably be put in its own repo in the nearest future.
