### ISSUE TITLE
[BUG] An Error Occurred

### ISSUE THREAD

**Issue by Ericmilon** [openprovider/OP-WHMCS7#167]
**Describe the bug**
Hi
I install your plugin but after run plugin for register domain i getting this error 

An Error Occurred
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'clientvp_cp.wHandles' doesn't exist (SQL: select * from `wHandles` where `data` = O:25:"OpenProvider\API\Customer":11:

**Comment by wmetge** [comment]
Hi @Ericmilon 

Thanks for bringing this to our attention. Here is a workaround:

https://github.com/openprovider/OP-WHMCS7/issues/85#issuecomment-632053911

This occasionally happens for some customers and we're trying to understand, could you indicate the WHMCS, PHP and MYSQL versions you are using?

also, I've removed the personal data from your comment on the off chance it is real data.

**Comment by Ericmilon** [comment]
Thank you my the problem fixed 
now I have new problem

An Error Occurred
Invalid telephone country code!

how can fix the problem I put valid phone number

WHMS: Version: 7.6.1
PHP: 7.3
erver: Localhost via UNIX socket
Server type: MySQL
Server connection: SSL is not being used Documentation
Server version: 5.7.34 - MySQL Community Server (GPL)
Protocol version: 10
User: cpses_un5j2pzbdg@localhost
Server charset: cp1252 West European (latin1)
Web server
cpsrvd 11.94.0.4
Database client version: libmysql - 5.6.43
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.3.27

**Comment by Ericmilon** [comment]
some one can help me? 
i write normal phone number but ever time I get the error 
An Error Occurred
Invalid telephone country code!

**Comment by wmetge** [comment]
Hi @Ericmilon , please contact Openprovider support with the specific customer details with which you are experiencing the issue.
