### ISSUE TITLE
Still receiving empty domain sync reports

### ISSUE THREAD

**Issue by DamageESP** [openprovider/OP-WHMCS7#17]
I updated the plugin, and I still receive empty Domain Sync reports.

Now I also receive an email saying "Error: action required before enabling Whois Privacy Protection".

The contract is signed since 2016...

**Comment by zubeldialuis** [comment]
Some problem. Blank emails recived randomly

**Comment by DamageESP** [comment]
Turns out this was happening because one of my domains (with .com.co TLD) apparently does not support ID Protection, so I was receiving an email for the WHOIS error, and the domain sync mail aswell.

I disabled the ID Protection, then tried to re-enable, and got the error saying that the TLD does not support it.

I don't seem to be getting more emails for now.
