### ISSUE TITLE
DNSsec not working [BUG]

### ISSUE THREAD

**Issue by BenMeesters** [openprovider/OP-WHMCS7#173]
**Describe the bug**
Cant update the DNSSEC setting, it will not write the info and it says the DNSsec is disabled. But DNSSEC is enabled and it reads the value set bij de openprovider panel

**To Reproduce**
log in as client and change dnssec

**Expected behavior**

**Screenshots**

**Server info:**
 - Distro: 
 - PHP: 
 - Web server: [e.g. httpd, nginx]

**Additional context**

**Comment by BenMeesters** [comment]
Hi,

Can someone help me out on this?

Regards, Ben

**Comment by wmetge** [comment]
Hi @BenMeesters thank you for reaching out to us. We're not able to replicate your issue. Would you be able to send the support team a ticket which includes the module log and the domain name in which this happens?

**Comment by BenMeesters** [comment]
Hi,

 

I don't see any problems in the module log, because no command is executed. The functions are simply not executed. 

Looks like some security is blocking the case. 

 

In addition, the response of the openprovider server is so slow that this is not a workable environment.

Same goes for the website and accountpanel  of openprovider. Slow…

 

I made screenshots for the explanation.

 



 

System reports that DNSSEC is not active, but as you can see it has a record.

Delete and Deactivate button are not responding

 



 

Function form ad DNSSEC record is responding but save is not working.

 

What the problem is a don’t know…but this will not work out off the box.

Hopefully you can fix this.

 

 

Met vriendelijke groet,

 

Ben Meesters


Van Schuppenstraat 5

5253DD Nieuwkuijk
T 073-8505242
 ***@***.***> ***@***.***

 

Van: wmetge ***@***.***> 
Verzonden: maandag 12 juli 2021 12:38
Aan: openprovider/OP-WHMCS7 ***@***.***>
CC: BenMeesters ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [openprovider/OP-WHMCS7] DNSsec not working [BUG] (#173)

 

Hi  <https://github.com/BenMeesters> @BenMeesters thank you for reaching out to us. We're not able to replicate your issue. Would you be able to send the support team a ticket which includes the module log and the domain name in which this happens?

**Comment by BenMeesters** [comment]
Any update on this isseu? as i wrote before I am using version 5.2 and when a use version 4.2 DNSSEC works.
So this is a programming fault. plz debug version 5.2

Regards

**Comment by BenMeesters** [comment]
Hi all,

I try to reach you by mail / ticket system, but no response unfortunately.

The DNSSEC system now works, but only works if dnsmanagement in whmcs is active. This should be changed to always available?

In addition, the current version gives problems with switching to other languages in the menu. Sometimes a fatal error and sometimes no translation.

Hopefully you can resolve this quickly.

Regards, Ben

**Comment by wmetge** [comment]
@BenMeesters thank you for the feedback, the issue has been resolved
