### ISSUE TITLE
Argument not found

### ISSUE THREAD

**Issue by danibrasa** [openprovider/OP-WHMCS7#21]
https://github.com/openprovider/OP-WHMCS7/blob/4d34f015c7f904519f960da388aefd0ecbfd1609/modules/registrars/openprovider/Library/Handle.php#L147

ArgumentCountError: Too few arguments to function OpenProvider\WhmcsRegistrar\Library\Handle::update(), 0 passed in public_html/modules/registrars/openprovider/Library/Handle.php on line 134 and exactly 1 expected 
fix ?
if($action == 'create')
            $this->findOrCreate($params, $type);
        else
            $this->update($params);

        return $this->model->handle;

**Comment by wmetge** [comment]
Hi @danibrasa, thanks for letting us know. Can you explain what the conditions were when this occurred? i.e. attempting domain registration / update / etc.

**Comment by soberoctober** [comment]
hi @danibrasa 

The module has been updated multiple times since October.
Please let us know if you still has this issue.
