### ISSUE TITLE
error change contacts

### ISSUE THREAD

**Issue by BenMeesters** [openprovider/OP-WHMCS7#23]
TypeError: Argument 1 passed to OpenProvider\WhmcsRegistrar\Library\Handle::checkIfHandleStillExists() must be an instance of WeDevelopCoffee\wPower\Models\Handle, boolean given, called in /modules/registrars/openprovider/Library/Handle.php on line 66 and defined in /modules/registrars/openprovider/Library/Handle.php:191

**Comment by BenMeesters** [comment]
PHP Version 7.0.30 fresh install WHMCS 7.6.1 seems like non of the register or domain tranfer is working as well.

**Comment by soberoctober** [comment]
hi @BenMeesters 
we are aware of that bug. could you please try registering the domain from the client area as a workaround?

**Comment by exhumept** [comment]
@soberoctober i have same error has @BenMeesters 

i am registering the domain from client area, after i have to accept the order/mark has paid using admin, register and transfers fail, error from registering attemp:

TypeError: Argument 1 passed to OpenProvider\WhmcsRegistrar\Library\Handle::checkIfHandleStillExists() must be an instance of WeDevelopCoffee\wPower\Models\Handle, boolean given, called in /whmcs/modules/registrars/openprovider/Library/Handle.php on line 66 and defined in /whmcs/modules/registrars/openprovider/Library/Handle.php:191
Stack trace:
/whmcs/modules/registrars/openprovider/Library/Handle.php(66): OpenProvider\WhmcsRegistrar\Library\Handle->checkIfHandleStillExists(false)
/whmcs/modules/registrars/openprovider/Controllers/Registrar/DomainController.php(69): OpenProvider\WhmcsRegistrar\Library\Handle->findOrCreate(Array)
/whmcs/modules/registrars/openprovider/openprovider.php(182): OpenProvider\WhmcsRegistrar\Controllers\Registrar\DomainController->register(Array)
[internal function]: openprovider_RegisterDomain(Array)
/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func('openprovider_Re...', Array)
/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call('RegisterDomain', Array)
/whmcs/includes/registrarfunctions.php(0): WHMCS\Module\Registrar->call('RegisterDomain', Array)
/whmcs/includes/registrarfunctions.php(0): RegCallFunction(Array, 'RegisterDomain')
/whmcs/includes/orderfunctions.php(0): RegRegisterDomain(Array)
/whmcs/admin/orders.php(0): acceptOrder(5, Array)
{main}

**Comment by BenMeesters** [comment]
Same result in the admin area, error....

**Comment by BenMeesters** [comment]
meaning to say client area

**Comment by exhumept** [comment]
Thank you @Exoid , the fix is workings for me.

Now registering and transfers works.

**Comment by BenMeesters** [comment]
Exoid, work fine.
Good job.

**Comment by coriaweb** [comment]
This solution worked for me.
