### ISSUE TITLE
When try to register domain

### ISSUE THREAD

**Issue by alexknobbe** [openprovider/OP-WHMCS7#24]
When i accept an domainorder in WHMCS i get the following page.

Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

TypeError: Argument 1 passed to OpenProvider\WhmcsRegistrar\Library\Handle::checkIfHandleStillExists() must be an instance of WeDevelopCoffee\wPower\Models\Handle, boolean given, called in /var/www/vhosts/......................................./modules/registrars/openprovider/Library/Handle.php on line 66 and defined in /var/www/vhosts/......................................./modules/registrars/openprovider/Library/Handle.php:191
Stack trace:
#0 /var/www/vhosts/......................................./modules/registrars/openprovider/Library/Handle.php(66): OpenProvider\WhmcsRegistrar\Library\Handle->checkIfHandleStillExists(false)
#1 /var/www/vhosts/......................................./modules/registrars/openprovider/Controllers/Registrar/DomainController.php(69): OpenProvider\WhmcsRegistrar\Library\Handle->findOrCreate(Array)
#2 /var/www/vhosts/......................................./modules/registrars/openprovider/openprovider.php(182): OpenProvider\WhmcsRegistrar\Controllers\Registrar\DomainController->register(Array)
#3 [internal function]: openprovider_RegisterDomain(Array)
#4 /var/www/vhosts/......................................./vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func('openprovider_Re...', Array)
#5 /var/www/vhosts/......................................./vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call('RegisterDomain', Array)
#6 /var/www/vhosts/......................................./includes/registrarfunctions.php(0): WHMCS\Module\Registrar->call('RegisterDomain', Array)
#7 /var/www/vhosts/......................................./includes/registrarfunctions.php(0): RegCallFunction(Array, 'RegisterDomain')
#8 /var/www/vhosts/......................................./includes/orderfunctions.php(0): RegRegisterDomain(Array)
#9 /var/www/vhosts/......................................./admin/orders.php(0): acceptOrder(2, Array)
#10 {main}

**Comment by alexknobbe** [comment]
I am running WHMCS version 7.6.1 and have PHP 7.2.11 with Apache

**Comment by soberoctober** [comment]
The development is working on a solution for that issue bur for now you can try registering your domains from the client area as a w/a.
