### ISSUE TITLE
Error in .es domains

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#25]
When we try to register a .es domain from WHMCS we get this error:

Ha habido problemas al aceptar el pedido
An unknown domain error has occurred; for more details, please refer to the registry message below:<br> Passport number or social security number cannot be blank

What can be done to solve this and to register domains from WHMCS?

**Comment by exhumept** [comment]
I have same issue, i think the OpenProvider module works with WHMCS custom fields that are not created by default

**Comment by wmetge** [comment]
Hi @coriaweb @exhumept ,

have you already added:

Added to resources/domains/additionalfields.php the following lines of code?

<?php
/**
* OpenProvider only overrides additional fields that are configured in WHMCS Domain Pricing with OpenProvider as registrar.
* Put this code above the other fields. Don't override additional fields manually for OpenProvider: we maintain this for you.
*/
$additionaldomainfields = openprovider_additional_fields();

**Comment by coriaweb** [comment]
That file doesn't exist in WHMCS. Can it be this file?

dist.additionalfields.php

**Comment by wmetge** [comment]
We will amend the readme, but if the additionalfields.php file does not exist, you can create one. Its method of operation is described in the WHMCS knowledge base: https://docs.whmcs.com/Additional_Domain_Fields

WHMCS does not reccommend making changes to the dist.additionalfields.php file.

from the admin area of the pending domain, do you see the following fields?
ID Form Type	
ID Form Number
Legal Form

**Comment by soberoctober** [comment]
installation instructions have been updated

**Comment by coriaweb** [comment]
In spite of doing everything they ask for in the installation, .es domains still give problems to register:

Ha habido problemas al aceptar el pedido
An unknown domain error has occurred; for more details, please refer to the registry message below:<br> Passport number or social security number cannot be blank
