### ISSUE TITLE
Error in the module

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#26]
When entering the module it shows an error:

URL: ******/addonmodules.php?module=openprovider

Error:

Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

If the problem persists, please contact us.

« Back to Homepage

For additional assistance, please reference the WHMCS TroubleShooting Guide »

Exception: NOT FOUND in *****/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/Dispatcher.php:131
Stack trace:
#0 *****/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/Dispatcher.php(85): WeDevelopCoffee\wPower\Controllers\Dispatcher->getControllerNameAndFunction()
#1 *****/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/AdminDispatcher.php(26): WeDevelopCoffee\wPower\Controllers\Dispatcher->dispatch('index', Array)
#2 *****/modules/addons/openprovider/openprovider.php(72): WeDevelopCoffee\wPower\Controllers\AdminDispatcher->dispatch('', Array)
#3 *****/addonmodules.php(0): openprovider_output(Array)
#4 {main}

**Comment by willdashwood** [comment]
Yes this issue doesn't seem to have been fixed. I just upgraded to latest version today (with all my fingers crossed) and this error is still there.

`Exception: NOT FOUND in /home/nginx/domains/ukhost4u.com/public/billing/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/Dispatcher.php:131
Stack trace:
#0 /home/nginx/domains/ukhost4u.com/public/billing/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/Dispatcher.php(85): WeDevelopCoffee\wPower\Controllers\Dispatcher->getControllerNameAndFunction()
#1 /home/nginx/domains/ukhost4u.com/public/billing/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/AdminDispatcher.php(26): WeDevelopCoffee\wPower\Controllers\Dispatcher->dispatch('index', Array)
#2 /home/nginx/domains/ukhost4u.com/public/billing/modules/addons/openprovider/openprovider.php(72): WeDevelopCoffee\wPower\Controllers\AdminDispatcher->dispatch('', Array)
#3 /home/nginx/domains/ukhost4u.com/public/billing/whmcsadmin/addonmodules.php(0): openprovider_output(Array)
#4 {main}`

**Comment by exhumept** [comment]
Issue #16 has been fixed, now is possible to activate the addon but when i try to open the addon it generate an error:

Exception: NOT FOUND in /whmcs/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/Dispatcher.php:131
Stack trace:
/whmcs/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/Dispatcher.php(85): WeDevelopCoffee\wPower\Controllers\Dispatcher->getControllerNameAndFunction()
/whmcs/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/AdminDispatcher.php(26): WeDevelopCoffee\wPower\Controllers\Dispatcher->dispatch('index', Array)
/whmcs/modules/addons/openprovider/openprovider.php(72): WeDevelopCoffee\wPower\Controllers\AdminDispatcher->dispatch('', Array)
/whmcs/admin/addonmodules.php(0): openprovider_output(Array)
{main}

**Comment by soberoctober** [comment]
6816c86026cf782c50624a117af1239f53a8f521
