### ISSUE TITLE
Change contacts info error:

### ISSUE THREAD

**Issue by exhumept** [openprovider/OP-WHMCS7#27]
Hi,

Trying to change domain contact info will pop up this error:

ArgumentCountError: Too few arguments to function OpenProvider\WhmcsRegistrar\Library\Handle::update(), 0 passed in /whmcs/modules/registrars/openprovider/Library/Handle.php on line 147 and exactly 1 expected in /whmcs/modules/registrars/openprovider/Library/Handle.php:270
Stack trace:
/whmcs/modules/registrars/openprovider/Library/Handle.php(147): OpenProvider\WhmcsRegistrar\Library\Handle->update()
/whmcs/modules/registrars/openprovider/openprovider.php(652): OpenProvider\WhmcsRegistrar\Library\Handle->updateOrCreate(Array, 'admin')
[internal function]: openprovider_SaveContactDetails(Array)
/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func('openprovider_Sa...', Array)
/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call('SaveContactDeta...', Array)
/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains.php(0): WHMCS\Module\Registrar->call('SaveContactDeta...', Array)
/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains.php(0): WHMCS\Domains->moduleCall('SaveContactDeta...', Array)
/whmcs/clientarea.php(0): WHMCS\Domains->saveContactDetails(Object(WHMCS\Client), Array, Array, Array)
{main}

**Comment by soberoctober** [comment]
hello @exhumept 
the issue has been fixed in one of the latest commits.
