### ISSUE TITLE
Error: action required before enabling Whois Privacy Protection

### ISSUE THREAD

**Issue by willdashwood** [openprovider/OP-WHMCS7#28]
Having got bitten by the WHOIS privacy logic bug I stayed on an old release until I thought everything was fixed. But I thought I'd give it another go recently and it seems that there's still some issues. The one I'm highlighting here related to enabling WHOIS protection on domains that are pending transfer. I just got the following email notification for a domain that hasn't yet transferred over to OpenProvider but it is pending. WHOIS privacy was enabled in WHMCS for the domain.

> Dear Administrator,
> 
> We send you this e-mail as a client or an administrator tried to enable identity protection for multiple domains. You did not sign the Whois Privacy Protection contract which is why the system was unable to process the request.
> 
> The domains:
> 
> DOMAINBEINGTRANSFERRED.com
> How to resolve this?
> 
> Navigate to the OpenProvider control panel.
> Click on Account -> Contracts
> Select "Whois Privacy Protection".
> When you agree, sign the contract.
> Navigate to WHMCS and search for every listed domain. When you are on a domain management page. Repeast step 6 and 7 for every domain. If the domain synchronisation is setup, this can be done automatically.
> If checked*, uncheck "ID Protection" and click on save.
> Check "ID Protection" and click on save.
> * WHMCS only sends the command to enable ID Protection when the checkbox was saved unchecked. Otherwise WHMCS will not send the command to enable identity protection.
> 
> When you have setup up domain synchronisation for OpenProvider the identity protection will also get enabled. However, depending on how you configured the synchronisation it may take up to a few days.
> 
> Regards,
> WHMCS powered by OpenProvider

**Comment by soberoctober** [comment]
@willdashwood can you send us the specific domain which you had an issue with? And we can check the error logs. 
Also, was the WPP contract signed, when you received this error?

**Comment by willdashwood** [comment]
Sorry I don't remember the domain name in question but yes the WPP contract has been signed for years.

The issue seems to be that when a domain name is pending transfer, this module tries to enable WHOIS protection, which understandably fails. I think there needs to be some logic in there that skips WHOIS protection if the domain status is pending transfer.

**Comment by willdashwood** [comment]
This has happened again with 2 domains I've just submitted for transfer. I don't want to post the domains in question publicly and can't PM on github it seems. So I've raised ticket ID 434638 on support.openprovider.eu and mentioned it's FAO @soberoctober 

Thanks

**Comment by soberoctober** [comment]
Confirmed, will be fixed in version 3.1.

**Comment by soberoctober** [comment]
resolved in [v3.1](https://github.com/openprovider/OP-WHMCS7/releases/tag/v3.1)
