### ISSUE TITLE
Error in .es domains

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#29]
In spite of doing everything they ask for in the installation, .es domains still give problems to register:

Ha habido problemas al aceptar el pedido
An unknown domain error has occurred; for more details, please refer to the registry message below:
Passport number or social security number cannot be blank

PD: I open it again because you've closed the other subject without being fixed.

**Comment by soberoctober** [comment]
hi @coriaweb 

would it be possible to share an exact createCustomerRequest call that was responded with the aforementioned error?
also, some details about the WHMCS client (company/individual, etc)

**Comment by soberoctober** [comment]
refer to #38
