### ISSUE TITLE
Additional fields problem

### ISSUE THREAD

**Issue by matiniamirhossein** [openprovider/OP-WHMCS7#31]
Dear OpenProvider,
There is an issue in your module that causes additional domain fields to not show in admin panel.

The problem is in the file named Path.php in modules\registrars\openprovider\vendor\wedevelopcoffee\wpower\src\Core

When loading from the admin panel, there is /admin in the document root.

I applied the fix by checking the last directory and if it's admin stripped it.

Here is the fixed code:
```
 public function getDocRoot()
    {
        global $customadminpath;
        if ($this->core->isCli()) {
            // DOC_ROOT does not work with cli
            // WARNING: This part of the code is not tested!
            $currentDir = __DIR__;
            $currentDirExploded = explode('modules', $currentDir);

            return $currentDirExploded[0];
        }

        $parts = explode(DIRECTORY_SEPARATOR, getcwd());
        if ($parts[sizeof($parts) - 1] == $customadminpath) {
            unset($parts[sizeof($parts) - 1]);
        }
        return implode(DIRECTORY_SEPARATOR, $parts);
    }
```

**Comment by soberoctober** [comment]
@matiniamirhossein thanks for pointing that out.
I believe the issue has been fixed in the latest commit.
The root cause was in incorrect path detection when WHMCS wasn't installed in the document root but a subdirectory.

**Comment by matiniamirhossein** [comment]
Thanks for you reply, I have the latest version (yesterday commit), can you double check?

**Comment by soberoctober** [comment]
@matiniamirhossein 

rolled out a fix, please try again.
