### ISSUE TITLE
Transferred Away Status for Domains

### ISSUE THREAD

**Issue by hostingwalk** [openprovider/OP-WHMCS7#32]
Since WHMCS 7.1 their is a Transferred Away Status for Domains

Maybe it can be implemented ?

**Comment by soberoctober** [comment]
@hostingwalk currently, it cannot be implemented since Openprovider API doesn't provide this info.

**Comment by willdashwood** [comment]
Could it not be implemented by maintaining a history of the domain's status? By that I mean, if the domain name is active and then on next sync is found to not exist in the OP account, it is assume to be transferred away.

**Comment by wmetge** [comment]
Hi @willdashwood, we have reservations about building in too many assumptions into the module, and expanding the logical complexity of the domain sync task. Take for example these cases:

**base case: Domain expires which has a quarantine period**
Openprovider status - ACT && WHMCS status - Active 
transition between sync: OP status from ACT to  DEL (grace period)
on sync: WHMCS status from Active to Grace 
transition between sync: OP status from  DEL (grace period) to domain not found
on sync: WHMCS status from Grace to Expired

**Transfer out case**
Openprovider status - ACT && WHMCS status - Active 
transition between sync: OP status from ACT to  DEL (domain not found)
on sync: WHMCS status from Active to Transferred away

In the base cases it works well, but there is an issue if a domain expires which doesn't have a quarantine (grace) period. 

**problem case: Domain expires which does not have quarantine period**: treated as "transfer out"
Openprovider status - ACT && WHMCS status - Active 
transition between sync: OP status from ACT to  DEL (domain not found)
on sync: WHMCS status from Active to Transferred away <-incorrect, should be "expired"

While most popular TLDs have grace and redemption periods, we offer move than 400 which do not. These are usually  country code TLDs (think .hotel.tz), and some of our module users are specifically using Openprovider for TLDs which are difficult to find elsewhere.

**Comment by willdashwood** [comment]
I agree, it's not a great solution and would be better implemented at API level rather than workaround in the WHMCS module. Also I'd say support for transferred away status is low down on the list of priorities.

**Comment by soberoctober** [comment]
not possible with current Openprovider API
