### ISSUE TITLE
Be able to specify DK-Handle during registration

### ISSUE THREAD

**Issue by lucasRolff** [openprovider/OP-WHMCS7#35]
When talking to the EPP service of DK-Hostmaster, DK-Hostmaster allows specifying the registrant and admin handle where the domain should be registered to (e.g. if customers want to use their existing DK-Hostmaster account for their newly registered domains).

It would be great if the OpenProvider WHMCS module could support supplying this registrant and admin handle (two individual fields in the DK Hostmaster EPP service).

This is especially important now where DK-Hostmaster charges 50 DKK (6.70 euro) for doing an ownership transfer.

**Comment by soberoctober** [comment]
@lucasRolff unfortunately, this feature is neither offered via Openprovider API nor are there plans to implement it.
