### ISSUE TITLE
Solve the problem with .es at once.

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#38]
Solve the problem with .es at once.

We have been having problems registering .es domains for a long time, we always have to end up doing things manually.

.es domains require the DNI or CIF field if it is a company. We need once and for all that the module solves this problem. 

The best option is that the module selects that data from one of the custom fields that we have already created, because for billing in Spain is mandatory the DNI, as an example, we have created this custom field: 

https://i.gyazo.com/63a095f10fb11b637ca3238bc0a40c07.png

Actually, when you are going to buy a .es it shows this:

https://i.gyazo.com/d949426980e2d0765fdacfb55a0b70ff.png

This is making us lose sales or even get many customers to contact us because they do not know what to do, it is not viable to show 4 fields, should only show 1, you should also have the option of translating it so that everyone can put it in our language.

You should take this seriously.

Translated with www.DeepL.com/Translator

**Comment by soberoctober** [comment]
the issue has been solved in 0dbd178abdf2be6db6dc66a046486a9181c6e5bf
