### ISSUE TITLE
Support "Pending Transfer" status

### ISSUE THREAD

**Issue by willdashwood** [openprovider/OP-WHMCS7#39]
The OpenProvider cron sets the status of domains that are in the process of being transferred from "Pending Transfer" to "Pending". I assume this is from when WHMCS didn't have the "Pending Transfer" status but perhaps this could be fixed now. Thanks

**Comment by soberoctober** [comment]
hello @willdashwood 

great idea, thanks, we're going to tweak the statuses for both transfer and grace periods.

**Comment by soberoctober** [comment]
6827882
