### ISSUE TITLE
Domain .es not sync transfer FAI stattus

### ISSUE THREAD

**Issue by zubeldialuis** [openprovider/OP-WHMCS7#4]
I do an order to transfer a domain .es

then the transfer was rejected. And domain in client area is always in "Pending" state.

**Comment by wmetge** [comment]
@zubeldialuis Thank you for the feedback. 

Please update the openprovider/OpenProvider/DomainSync.php file from the latest release: https://github.com/openprovider/OP-WHMCS7/releases/tag/2.2.3 

This should solve your issue
