### ISSUE TITLE
Module shouldn't convert things to ascii

### ISSUE THREAD

**Issue by lucasRolff** [openprovider/OP-WHMCS7#42]
When the module calls the API to create contacts (`createcustomerrequest` as an example), it seems to be converting characters to ascii, but it converts it incorrectly.

Let's say we create the customer:
```
Name: Jørgen Ågard
Address: Tøtmosen 3a
City: København
Postcode: 9800
State: Sønderjylland
```

It seems when you're actually doing the API call `createcustomerrequest` the data submitted will be in ASCII:
```
Name: Jorgen Agard
Address: Totmosen 3a
City: Kobenhavn
Postcode: 9800
State: Sonderjylland
```

The module shouldn't convert the characters, and if it's required because OpenProvider doesn't support UTF-8, then they should be converted into the correct international representation:
```
æ = ae
ø = oe
å = aa
Æ = Ae
Ø = Oe
Å = Aa 
```

Currently it will cause address validation to fail for the DK-registry because `Kobenhavn` isn't equal `København` - this failure in the DK-registry results in the domain eventually being canceled because it won't be validated within the 3 days period required by the registry.

**Comment by wmetge** [comment]
Hi @lucasRolff, thanks for bringing this to our attention. We'll take a look at it soon.

**Comment by soberoctober** [comment]
@lucasRolff this is a WHMCS issue.

Here's their response:

> I have been able to replicate this behavior on my end as well. I have opened Case ID CORE-13427 with our development team in order to have this reviewed for future releases.
> Unfortunately, I cannot provide an estimated time for completion for this. However, once we resolve cases and push features they are available at our change log at http://changelog.whmcs.com/
> I apologize for the inconvenience, and appreciate your patience as we work to resolve this.
