### ISSUE TITLE
You are about to register the premium domain

### ISSUE THREAD

**Issue by willdashwood** [openprovider/OP-WHMCS7#44]
When trying to register a premium domain the following error is returned.

> You are about to register the premium domain. If you accept this registration fee, re-send the createDomainRequest and add the parameters "acceptPremiumFee" with the value of a premium fee, which can be found in the `data` block of this command output.:<br> 42

It would be great if instead of just throwing an error, there could be a prompt to proceed. Or if that's not technically possible, perhaps adding another checkbox to accept the premium fee. At the moment we just have to register these domains manually.

Now that WHMCS and the module support premium domain look prices (which is working) I think this also needs addressing.

Thanks

**Comment by soberoctober** [comment]
fixed in [v3.0](https://github.com/openprovider/OP-WHMCS7/tree/v3.0)
