### ISSUE TITLE
Exclude domain from domainsync

### ISSUE THREAD

**Issue by thomashoeky** [openprovider/OP-WHMCS7#45]
Hello,

I would like to be able to exclude domains from the openprovider domainsync because I want to invoice customers once a month, so I have to edit the due date of the domains. I would like to keep the DNS of WHMCS working for the domains

Is this possible?

**Comment by wmetge** [comment]
Hi @thomashoeky ,

Currently there is no mechanism within the module for excluding domains from the domainsync. If you want to exclude all Openprovider domains from syncing the due date and expiration date, you could potentially comment out the "process_expiry_and_due_date()" function from the file "/modules/registrars/openprovider/OpenProvider/DomainSync.php"  as indicated below:

`
                // Set the expire and due date -> openprovider is leading
               // $this->process_expiry_and_due_date(); ***comment out this function***

                // Active or pending? -> openprovider is leading
                $this->process_domain_status();

                // auto renew on or not? -> WHMCS is leading.
                $this->process_auto_renew();

                // Identity protectionon or not? -> WHMCS is leading.
                $this->process_idenity_protection();
`

if you only want certain to be skipped, you could potentially make a check in the process_domains() function, to filter out the desired domains.

**Comment by thomashoeky** [comment]
Thank you, I will look into this and post a update/share the code 👍

**Comment by wmetge** [comment]
thank you!

**Comment by thomashoeky** [comment]
It looks like im not able to debug the DomainSync file because it wont save variables to a text file.
Is $domain a string with the domain name (a few lines above your snippet)? If so I could make a file with the domains listed and check if $domain is in that file to exclude it from only $this->process_expiry_and_due_date();

**Comment by thomashoeky** [comment]
https://github.com/openprovider/OP-WHMCS7/pull/46

**Comment by soberoctober** [comment]
In [v3.0](https://github.com/openprovider/OP-WHMCS7/tree/v3.0) it is now possible to not sync Expiry date, status and couple of other things when running DomainSync.php:
![Screenshot 2019-09-18 at 13 05 35](https://user-images.githubusercontent.com/19632372/65118452-4b0fb600-da15-11e9-8bea-3e093f7526b5.png)
