### ISSUE TITLE
DNS Manager - Add more record Types 

### ISSUE THREAD

**Issue by kess78** [openprovider/OP-WHMCS7#49]
Hello guys,
actually the DNS Manager (through WHMCS client area /clientarea.php?action=domaindns&domainid=1234) allows management of records of type: A, AAAA, MXE, MX, CNAME, TXT, URL, FRAME.

It would be nice to see also records like: CAA, SRV, TLSA, SSHFP, TSDNS. The most important is for sure SRV record !

Some Others did that already, example here: https://github.com/inwx/WHMCS/blob/master/modules/registrars/internetworx/hooks.php

Would it be possible to do it in OP also ?

Thx for your feedback

**Comment by soberoctober** [comment]
hey @kess78 

Great suggestion! Advanced DNS management functionality is not our most demanded feature, however we'll definitely assess the possibility of reaching record type parity with Openprovider's API.

**Comment by mbblcnetworks** [comment]
Would be nice also to add the feature to be able to see private nameservers records.

At the moment we can add, modify and remove private nameservers records but we cant see the actually record list.

**Comment by soberoctober** [comment]
Version 3.3 introduces [DNS record type parity](https://github.com/openprovider/OP-WHMCS7#install-the-dns-management-options) with Openprovider nameservers.
