### ISSUE TITLE
WHMCS Domain Synchronisation Cron Report

### ISSUE THREAD

**Issue by solucionesuno** [openprovider/OP-WHMCS7#50]
I recive a lot of times a day an email with the Subject
WHMCS Domain Synchronisation Cron Report

And content:

Active Domain Syncs
- *****.com: Expiry Date updated to 28/11/2019

The problem is that the domains are ever the same.

i check for the expiry date for domain in whmcs and is the same that the cron email report to me.

Whats happens?

Thanks
Luis.

**Comment by soberoctober** [comment]
Hi @solucionesuno 

Yes, we are aware about the issue. Our module follows the following sync logic now: 
the synchronisation of the next due date is only allowed when the difference is no more than 60 days compared to the expiry date. 

This rule appears to be ineffective in many cases, so we have decided to revise it in a new framework that is going to be introduced in version 3.0

**Comment by solucionesuno** [comment]
Mmmmmm seems that this emails is generated by WHMCS SYNC domain, not by openprovider plugin??

So i try now to disable native whmcs Domain Sync in ---> Setup > Automation Settings -->
Domain Sync Enabled 

I understand that like OP has his own cron for the domain sync proces, native whmcs sync must be disabled?

I can not find any mention about this in the plugin documentation.

Thanks.

**Comment by solucionesuno** [comment]
Please can you clarify the follow:

*******
Note that WHMCS has a different script, cron.php, which it uses to perform many of its functions, including generating invoices, and syncing domain statuses with other registries. The DomainSync script from Openprovider is in addition to the WHMCS cron job, and needs to be scheduled separately. As the impementation of WHMCS to synchronize the domain status is limited, a separate cron is required.
***********

the cron of OP_WHMCS needs of the WHMCS SYNC DOMAINS NATIVE, or native syn can be disabled?

**Comment by soberoctober** [comment]
hi @solucionesuno 

>Mmmmmm seems that this emails is generated by WHMCS SYNC domain, not by openprovider plugin??

You're absolutely right. The module sends a report only at the time of DomainSync.php script's execution.

>I understand that like OP has his own cron for the domain sync proces, native whmcs sync must be disabled?

Yes, that is correct, however we never mention that the default sync should be disabled. Openprovider's script should be used in addition to WHMCS' tool.

As a temporary w/a you can try disabling due date sync in Setup -> Automation -> Sync Next Due Date.

**Comment by soberoctober** [comment]
resolved in [v3.1](https://github.com/openprovider/OP-WHMCS7/releases/tag/v3.1)
