### ISSUE TITLE
Error in OP 3.0

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#52]
Error 500:

Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

Whoops\Exception\ErrorException: Declaration of DI\Definition\EntryReference::getDefinition($entryName) must be compatible with DI\Definition\Helper\DefinitionHelper::getDefinition(string $entryName): DI\Definition\Definition in *****/modules/addons/openprovider/vendor/php-di/php-di/src/DI/Definition/EntryReference.php:14
Stack trace:
#0 *****/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'Declaration of ...', '/home/coriaweb/...', 14)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

**Comment by soberoctober** [comment]
fixed in 29265de563dbd8f405d69fcb302ae7a86ad69863
