### ISSUE TITLE
Error: Call to undefined function wLaunch() in /modules/addons/openprovider/openprovider.php:74

### ISSUE THREAD

**Issue by hostingwalk** [openprovider/OP-WHMCS7#54]
Error: Call to undefined function wLaunch() in /modules/addons/openprovider/openprovider.php:74
Stack trace:
#0 /public_html/admin/addonmodules.php(0): openprovider_output(Array)
#1 {main}

I still have this issue.

_Originally posted by @hostingwalk in https://github.com/openprovider/OP-WHMCS7/issues/51#issuecomment-532615621_

**Comment by soberoctober** [comment]
hi @hostingwalk 

could you please share your php version and the distribution you're hosting your WHMCS on?

**Comment by soberoctober** [comment]
fixed in 29265de563dbd8f405d69fcb302ae7a86ad69863
