### ISSUE TITLE
process_domains update_domain_data bug

### ISSUE THREAD

**Issue by tmishutin** [openprovider/OP-WHMCS7#6]
Hi.

There is a bug with domainSync. In some cases, $this->update_domain_data won't be resetted and will go to the next iteration. If there is nothing to update on the next iteration it will still be updated with old data from $this->update_domain_data.

Fix: move $this->update_domain_data = null; to the begin of the loop.

`
		$this->OpenProvider = new OpenProvider;

		foreach($this->domains as $domain)
		{
    		$this->update_domain_data = null;

			try
...........
`

**Comment by MrKoopie** [comment]
I noticed that this one is still open. It is fixed in #813dac0dc56553947c32c6ee1e40f4fa442e1031 .
