### ISSUE TITLE
Route doesn't exist

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#62]
I have installed a module in WHMCS for resellers of garden modules domains, in all calls from the api I have this error:

Ha ocurrido un error
Route does not exist.:

I'm told it may be a recorder failure. Do you know if it's true?

Greetings!

**Comment by soberoctober** [comment]
@coriaweb 

Could you provide us the steps to reproduce this?
Also, maybe check [this PR](https://github.com/vvolv/OP-WHMCS7/commit/841b6c366b4d07b6a17c6107c23199219b9181ec) in the meantime.

**Comment by coriaweb** [comment]
Yes, the error was corrected by the indicated solution.

Greetings!
