### ISSUE TITLE
Route does not exist - from WHMCS API

### ISSUE THREAD

**Issue by vvolv** [openprovider/OP-WHMCS7#64]
# Steps to reproduce
1. Create "test" directory in WHMCS root.
2. Create "test.php". 
3. Insert code
```php
<?php

require_once './../init.php';
$command = 'DomainGetNameservers';
$postData = array(
    'domainid' => '1008',
);
$results = localAPI($command, $postData);

echo '<pre>';
print_r($results);
```

# What is wrong? 
Path in method getDocRoot is wrongly calculated https://github.com/openprovider/OP-WHMCS7/blob/v3.2/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Path.php#L33

**Comment by soberoctober** [comment]
Fixed in 1baba70
