### ISSUE TITLE
Call to undefined method WeDevelopCoffee\wPower\Core\Core::setModuleName()

### ISSUE THREAD

**Issue by DAThosting** [openprovider/OP-WHMCS7#66]
Getting the following error while browsing to configregistrars.php

`Error: Call to undefined method WeDevelopCoffee\wPower\Core\Core::setModuleName() in /path/to/whmcs/modules/registrars/openprovider/init.php:24
Stack trace:
#0 /path/to/whmcs/modules/registrars/openprovider/init.php(13): openprovider_registrar_core('system')
#1 /path/to/whmcs/modules/registrars/openprovider/openprovider.php(43): openprovider_registrar_launch('system')
#2 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): openprovider_getConfigArray(Array)
#3 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call('getConfigArray', Array)
#4 /path/to/whmcs/support/configregistrars.php(0): WHMCS\Module\Registrar->call('getConfigArray')
#5 {main}`

WHMCS: 7.8.3
OpenProvider-Module: latest (downloaded today)
PHP: 7.3.12

**Comment by soberoctober** [comment]
hi @DAThosting 

Did you actually redact the path to your WHMCS installation?
This stack trace looks like something was put out of its place.

**Comment by DAThosting** [comment]
I've changed the path here in the issue, cause there are some private folders ;)
The module worked before the upgrade without problems.

**Comment by DAThosting** [comment]
Same in addons:

`Error: Call to undefined method WeDevelopCoffee\wPower\Core\Core::setModuleName() in /path/to/whmcs/modules/addons/openprovider/init.php:23
Stack trace:
#0 /path/to/whmcs/modules/addons/openprovider/init.php(12): openprovider_addon_core('admin')
#1 /path/to/whmcs/modules/addons/openprovider/openprovider.php(74): openprovider_addon_launch('admin')
#2 /path/to/whmcs/support/addonmodules.php(0): openprovider_output(Array)
#3 {main}`

**Comment by DAThosting** [comment]
Can't find any problem.
Don't know what exactly is the issue which effect this.

I can't register, transfer, renew or change anything in whmcs, everytime this error occurs.

**Comment by DAThosting** [comment]
Why WeDevelopCoffee is needed? Could this removed? @soberoctober

**Comment by soberoctober** [comment]
Hi @DAThosting 

Sorry for a delayed response.

First and foremost, yes, WeDevelopCoffee is absolutely necessary for the module to operate.

Just to make sure we're on the same page:

1. You've been running version 3.1 before upgrading to the release from 3.2 branch
2. You've updated by replacing all the files in both ~whmcs/modules/registrars/openprovider and ~whmcs/modules/addons/openprovider
3. After the update the aforementioned error is being thrown on configregistrars.php page

Have you tried reinstalling the module from scratch rather than just updating?

Which OS is running on your server?

**Comment by DAThosting** [comment]
Hi

1. Exactly
2. Jep
3. Not only configregistrars.php, all pages which have to do something with domains.

Yes I have removed everything with openprovider and reinstalled it like a new install.

I running Plesk Obsidian 18.0.21 on ‪Debian 9.11‬.

**Comment by DAThosting** [comment]
I deleted Openprovider SSL Module, installed Domain Module again and after that installing SSL Module...

Now it works. Don't ask me why :D
