### ISSUE TITLE
OpenProvider timeout

### ISSUE THREAD

**Issue by AmazingDreams** [openprovider/OP-WHMCS7#67]
I am using an older / alternative version of this module. However I regularly get timeout errors on the openprovider apis. Initially the curl timeout was set to 1000 by default. I changed this value to 30 seconds in order not to mess up our crons. The root cause appears to be a timeout at the OpenProvider endpoint.

Please advice.

**Comment by wmetge** [comment]
Thank you for informing us @AmazingDreams. This might be an issue which the Openprovider support team can help you with. Please create a ticket either via email or via the control panel. Please specify your account number, and if possible, briefly explain how the alternative module you are using is different from the current one.
