### ISSUE TITLE
Error: Call to undefined method WeDevelopCoffee\\wPower\\Core\\Core::setModuleName()

### ISSUE THREAD

**Issue by tamerciaga** [openprovider/OP-WHMCS7#71]
Hello,

Today we updated the OP module (in the hope that it would fix some issues). We tried version 3.1 and 3.2, with both versions we get the following error:

`[WHMCS Application] ERROR: Error: Call to undefined method WeDevelopCoffee\\wPower\\Core\\Core::setModuleName() in /path/to/whmcs/modules/registrars/openprovider/init.php:24 Stack trace: #0 /path/to/whmcs/modules/registrars/openprovider/init.php(13): openprovider_registrar_core('system') #1 /path/to/whmcs/modules/registrars/openprovider/openprovider.php(80): openprovider_registrar_launch('system') #2 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): openprovider_GetNameservers(Array) #3 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\\Module\\AbstractModule->call('GetNameservers', Array) #4 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains.php(0): WHMCS\\Module\\Registrar->call('GetNameservers', Array) #5 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains.php(0): WHMCS\\Domains->moduleCall('GetNameservers') #6 /path/to/whmcs/admin/clientsdomains.php(0): WHMCS\\Domains->getDomainInformation() #7 {main} {"exception":"[object] (Error(code: 0): Call to undefined method WeDevelopCoffee\\\\wPower\\\\Core\\\\Core::setModuleName() at /path/to/whmcs/modules/registrars/openprovider/init.php:24)"} []`

We are using WHMCS 7.9.2 and we are using this in production, so we are a bit disappointed overal about this module. I'm not sure which version we where using as we kept delaying the update due to these kinds of issues (and I can't find any versioning in the code, not even in the module version param).

Do you have any idea where to start?

**Comment by soberoctober** [comment]
hi @tamerciaga,

we're sorry that you're getting these kind of issue with the module.

can you try installing the version from this archive and letting me know the outcome?
[openprovider-master.zip](https://github.com/openprovider/OP-WHMCS7/files/4444707/openprovider-master.zip)

**Comment by tamerciaga** [comment]
Hi @soberoctober thank you for your reply.

The master is what I tried today (seems to be version 3.2).

**Comment by MrKoopie** [comment]
@tamerciaga Looks like the vendor directory and its contents is missing. Can you check that the following exists?

modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Core.php

**Comment by tamerciaga** [comment]
Hey, the file modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Core.php exists in my zip. The wedevelopcoffee folder seems to be properly filled.

**Comment by MrKoopie** [comment]
@tamerciaga Just to be sure, can you confirm that it exists on the server as well with the setModuleName method? Also, check if `modules/registrars/openprovider/vendor/wedevelopcoffee/wPower` exists on your production server and remove it.

**Comment by tamerciaga** [comment]
@MrKoopie thanks, I confirmed it and the method setModuleName exists.
Also `modules/registrars/openprovider/vendor/wedevelopcoffee/wpower` exists and is properly uploaded with the new files.

**Comment by MrKoopie** [comment]
Have you uploaded the addon module? If so, make sure this one is also up-to-date. It looks like you have wPower in use with another module which is not up-to-date with the latest wPower module.

**Comment by tamerciaga** [comment]
@MrKoopie you where partially right about `modules/registrars/openprovider/vendor/wedevelopcoffee/wPower`. But that was not the folder that should be removed on the server.

The addon module uses `wPower` instead of `wpower`, so I removed `wpower` (probably the older module used it). However, the registrar module uses `wpower` instead of `wPower`. So that's a bit inconsistent.

It works now...so thanks for the help and remember this for those who update from an older version.

**Comment by MrKoopie** [comment]
You are welcome. I will check if we can present a warning or something when the incorrect folder exists.

Can you close this issue?
