### ISSUE TITLE
Support for new registrar TLD Sync

### ISSUE THREAD

**Issue by ssergio-ll** [openprovider/OP-WHMCS7#72]
Please, can you add support for new Registrar TLD Sync. 

More info: 

[https://docs.whmcs.com/Registrar_TLD_Sync?utm_source=in-product&utm_medium=whatsnew710]

Thanks.

**Comment by wmetge** [comment]
@ssergio-ll Thanks for the feedback, this feature will be in the next release

**Comment by soberoctober** [comment]
release in [3.3](https://github.com/openprovider/OP-WHMCS7/releases/tag/v3.3)

**Comment by ssergio-ll** [comment]
This don't run correctly. I have a suscription on Openprovider (Basic up to 100 domains). The domain prices are assumed to be at cost price. For example ".eu" for register should be 1,75 €, but whmcs openprovide module when sync show that cost is 5.95 €.
