### ISSUE TITLE
The new support for registrar TLD Sync don't run correctly

### ISSUE THREAD

**Issue by ssergio-ll** [openprovider/OP-WHMCS7#75]
This don't run correctly. I have a suscription on Openprovider (Basic up to 100 domains). The domain prices are assumed to be at cost price. For example ".eu" for register should be 1,75 €, but whmcs openprovide module when sync show that cost is 5.95 €.

**Comment by MrKoopie** [comment]
Replace the following

https://github.com/openprovider/OP-WHMCS7/blob/1f81b658c3091adf712d08bdbf86bf07e54b24f1/modules/registrars/openprovider/Controllers/System/TldPricingController.php#L66-L67

with
```
            if(isset($extension['prices']['resellerPrice']['reseller']['price']))
                $item->setRegisterPrice($extension['prices']['resellerPrice']['reseller']['price']);
            elseif(isset($extension['prices']['createPrice']['reseller']['price']))
                $item->setRegisterPrice($extension['prices']['createPrice']['reseller']['price']);
```

**Comment by ssergio-ll** [comment]
Ok, thanks. It run but now when i go to import, the table don't show profit Margin. I attatch a capture:

![Screenshot_20200430_104314](https://user-images.githubusercontent.com/22059282/80690956-d5ea8000-8acf-11ea-8e1b-d22acddf0000.png)

**Comment by MrKoopie** [comment]
@ssergio-ll That happens when the TLD does not exist in WHMCS yet with a price. The margins and prices you find there, are the current margins when the TLD exists in WHMCS.
