### ISSUE TITLE
White screen on dashboard after active

### ISSUE THREAD

**Issue by parisdeveloper** [openprovider/OP-WHMCS7#76]
Not connect error 196 and white screen on dashboard, i test on 2 WHMCS.

**Comment by wmetge** [comment]
@parisdeveloper We're happy to help you with any issue regarding the module. A 196 error from the Openprovider API indicates that your credentials are incorrect.

If you don't already have an account, you can sign up for free at [https://rcp.openprovider.eu/registration.php](https://rcp.openprovider.eu/registration.php)

If you already have an account, please ensure you are using the correct password for an account with API access enabled. 

If your problems persist, feel free to contact the Openprovider support team directly, and a support engineer will be able to give you direct assistance.
