### ISSUE TITLE
[BUG] The price synchronization doesn't work

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#77]
The price synchronization doesn't work, I access the tool and it stays that way:

https://i.gyazo.com/3e147174a37afc4f8a1721798361a11e.png

After a while it does nothing and stays like this:

https://i.gyazo.com/8003a5a279e081dd4ca62d895f641f03.png

What happens?

**Comment by MrKoopie** [comment]
The module requires a significant amount of time (2 - 5 minutes). This is mostly because the Openprovider API needs time to calculate the prices specified for your account. Chances are that a timeout occurred.

Can you open up the developer tools and click Openprovider after that? Also, make sure to check the logs.

**Comment by theemstra** [comment]
We've ran into the same issue, we've extended the timeout options and set it to the max available value (2 minutes), but it still times out. Is there a way to reduce the time it takes to fetch the data, or maybe do this in batches (and/or during cron), to prevent timeouts?

**Comment by MrKoopie** [comment]
@theemstra You could set the timeout to 0 (unlimited) but there should not be any limits. As WHMCS does not support batched loading of data, we are limited to what is supported here.

Also; make sure that your webserver can handle the loading time.

There are a few alternatives, but I do not really like them. The best solution would be that Openprovider improves the loading speed and that WHMCS supports batches.

An alternative option might be where the data is downloaded in batches (outside the TLD sync feature) and that you have to click like 5 times to load it. It is not a pretty solution, but it might just work. What do you think?

**Comment by theemstra** [comment]
Hi @MrKoopie thanks for your prompt reply.

Of course, this is all depending on the environment used and how much control the user of this add-on has over the hosting environment.

I think the best option between now and WHMCS supporting sync-batches (which will probably not be soon) is that the add-on keeps track of which TLD-data is synchronized and syncs them batch by batch (like with the domainsync, those are synced in batches too, based on user setting in add-on settings), and based on how much can be synced every time, the admin has to click a few times to sync all the different TLD information.

**Comment by coriaweb** [comment]
I've already solved it by increasing the timeout php and ProxyTimeout values.

Thank you!

**Comment by spylex** [comment]
I had the same issue, increased timeout in PHP to 600 seconds and memory allocation to 512mb helped as it was needing just over 256mb.

**Comment by soberoctober** [comment]
General recommendations to troubleshoot the issue:

1. enable System Module Debug Log in WHMCS
2. [increase `max_execution_time` and `max_input_time` for PHP scripts](https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time)
3. start TLD Price sync
4. if the page went blank, check the logs, make sure searchextensionrequest is being called
5. if it is, find whether or not the response is cut off abruptly (the XML is invalid, <openXML> tag isn't closed, etc)
6. if point 5 is true, then the execution is most probably terminated by the timeout of the web server.
7. try increasing TimeOut directive in the [config file of httpd service](https://httpd.apache.org/docs/2.4/mod/core.html#timeout) or its equivalent for nginx
8. restart the sync

**Comment by soberoctober** [comment]
@spylex thanks for sharing your experience, however, I must say that memory consumption is unlikely to be associated with the problem. During my tests I've rarely seen a php-fpm process using more than 40MB of memory. It might have been an issue of memory allocation in your case, though.

**Comment by spylex** [comment]
I have GBP as my main currency, but in the server error logs it was trying to allocate 260mb of memory and erroring out when it was executing - wonder if that was it!

**Comment by soberoctober** [comment]
Troubleshooting steps are available in [this KB article](https://support.openprovider.eu/hc/en-us/articles/360014143399-Registrar-TLD-Pricing-Sync-Utility-doesn-t-work-blank-page-is-shown-when-running-the-sync)
