### ISSUE TITLE
Inconsistency with price synchronization.

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#78]
I see that there is an "incongruity".

If I go to the system, I see this price:

https://i.gyazo.com/60fefd333fe6390c5798bee8fbf5b0c7.png

But that's not the base price, it's taking a price assigned to a group of resellers, I put example images:

Base price: https://i.gyazo.com/223f353f3ebce0d4e5652968a004381e.png

Reseller group price: https://i.gyazo.com/4a77f07e074d9fbe264dee229d8e716f.png

It's kind of weird, isn't it? You should only pay attention to the default base price, you should not change or show any other group.

**Comment by MrKoopie** [comment]
Did you check out this fix?
https://github.com/openprovider/OP-WHMCS7/issues/75#issuecomment-621657510
