### ISSUE TITLE
[BUG] Call to a member function getSecondLevel() on null in DomainInformationController.php

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#79]
We have some customers with a reseller module running via the API from their WHMCS. 

Since yesterday's update, the email they received with the domain synchronization shows errors, if I look at the server log, I get these errors:

`[Tue May 05 14:35:39.342257 2020] [proxy_fcgi:error] [pid 19467:tid 139919002126080] [client ********] AH01071: Got error 'PHP message: [WHMCS Application] ERROR: Error: Call to a member function getSecondLevel() on null in /*****/modules/registrars/openprovider/Controllers/System/DomainInformationController.php:44 Stack trace: #0 /*****/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Instance.php(47): OpenProvider\\WhmcsRegistrar\\Controllers\\System\\DomainInformationController->get(Array) #1 /*****/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Launch.php(54): WeDevelopCoffee\\wPower\\Core\\Instance->execute('get', Array) #2 /*****/modules/registrars/openprovider/openprovider.php(81): WeDevelopCoffee\\wPower\\Core\\Launch->output(Array, 'GetDomainInform...') #3 /*****/modules/addons/domainreseller/api.php(0): openprovider_GetDomainInformation(Array) #4 {main} {"exception":"[object] (Error(code: 0): Call to a member function getSecondLev...'`

Do you know what that could be?

**Comment by MrKoopie** [comment]
@coriaweb Do you mean this module? https://www.modulesgarden.com/products/whmcs/domains-reseller

It looks like that module is nog providing all information WHMCS does. WHMCS provides the original params, which in this case is missing. You can ask Modulesgarden to fix the bug in their module first.

https://github.com/openprovider/OP-WHMCS7/blob/ad780adead882163d7d7eeabba594cc6f9bd47bf/modules/registrars/openprovider/Controllers/System/DomainInformationController.php#L44

**Comment by coriaweb** [comment]
https://whmcs.com.ua/products/domain-reseller/?language=english

This is the module, I already contacted them before writing here and they tell me that it is your problem.

If I need to write something else, please let me know.

Greetings!

**Comment by MrKoopie** [comment]
@coriaweb Interesting since they deviate from WHMCS standards. I will have a look at this.

Could you, by any chance, replace the code with [url=https://gist.github.com/MrKoopie/466ae4149b8c24eb281c2dcaec11c30e]this[/url], update YOURPATH with a local path you can write to (e.g. /home/whmcs/DomainInformationController_get.log) so I can check out what information is available and tun the synchronization?

Do not forget to remove the login data. Use a staging environment when possible.

**Comment by coriaweb** [comment]
> @coriaweb Interesting since they deviate from WHMCS standards. I will have a look at this.
> 
> Could you, by any chance, replace the code with [this](https://gist.github.com/MrKoopie/466ae4149b8c24eb281c2dcaec11c30e), update YOURPATH with a local path you can write to (e.g. /home/whmcs/DomainInformationController_get.log) so I can check out what information is available and tun the synchronization?
> 
> Do not forget to remove the login data. Use a staging environment when possible.

Hello!

Sorry I'm late, but it was impossible for me to try this before.

I tried and I put:

file_put_contents("/home/****/public_html/****/modules/registrars/openprovider/Controllers/System/DomainInformationController_get.log", print_r($params, 1));

But the log is not written, it remains empty.

Strange, isn't it?
