### ISSUE TITLE
Error en renovación desde WHMCS

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#8]
Al pinchar en renovar desde WHMCS muestra el siguiente error:

Domain not in soft quarantine period. Needs to be manually restored

¿Cómo puede solucionarse?

El caso es que me he dado cuenta que en openprovider si se ha cobrado cada vez que he pinchado, a pesar del error.

Saludos!

**Comment by wmetge** [comment]
Thank you for the feedback! fixed in the release 2.2.6
