### ISSUE TITLE
Prevent order if domainlock is active

### ISSUE THREAD

**Issue by DAThosting** [openprovider/OP-WHMCS7#80]
FEATURE REQUEST:

If a domain should be transfered and this domain is in the 60 day lock (or other) then the customer should get a notice.
If he want to transfer, then allow the order and send the transfer request to OP-API with the specific date.
Else no order will be placed.

**Comment by MrKoopie** [comment]
@DAThosting this is a feature that WHMCS should implement. The module is only triggered once a payment or registration action happened, not before that.

**Comment by soberoctober** [comment]
FR to WHMCS should be submitted.
