### ISSUE TITLE
[BUG] SRV record can neither be added nor displayed in the DNS zone

### ISSUE THREAD

**Issue by DAThosting** [openprovider/OP-WHMCS7#81]
I installed the module as written in readme.
The problem is, in RCP the records are visible but not at the customer whmcs interface.
A, AAAA, MX and CNAME are visible, but not srv, soa etc.

Also SRV needs a priority, so a change in clientareadomaindns.tpl have to be done.
Change this:
`{if $dnsrecord.type eq "MX"}<input type="text" name="dnsrecordpriority[]" value="{$dnsrecord.priority}" size="2" class="form-control" />{else}<input type="hidden" name="dnsrecordpriority[]" value="N/A" />{$LANG.domainregnotavailable}{/if}`
to this:
`{if $dnsrecord.type eq "MX" || $dnsrecord.type eq "SRV"}<input type="text" name="dnsrecordpriority[]" value="{$dnsrecord.priority}" size="2" class="form-control" />{else}<input type="hidden" name="dnsrecordpriority[]" value="N/A" />{$LANG.domainregnotavailable}{/if}`

Module Version v3.3
WHMCS V7.8.3

**Comment by soberoctober** [comment]
Hi @DAThosting 
Thanks for your investigation. The issue with SRV record type has been acknowledged.
We'll try to address this in the upcoming update to the module.

We'll research the possibility of adding NS and SOA records as greyed out entitles since these types of records cannot be changes by the end-user.

**Comment by DAThosting** [comment]
I found the APIConfig.php inside the API folder.
Then I uncommented the line with all supported DNS types and implemented the following for clientareadomaindns.tpl so NS and SOA are greyed out and can't be edited.

Right under {foreach from=$dnsrecords item=dnsrecord} set:
`{if $dnsrecord.type eq "SOA" || $dnsrecord.type eq "NS"}{assign "OP_blockedns" "disabled"}{else}{assign "OP_blockedns" ""}{/if}`

Now on each <td> in this foreach add {$OP_blockedns} at the end of a input:
` <tr>
                    <td><input type="hidden" name="dnsrecid[]" value="{$dnsrecord.recid}" /><input type="text" name="dnsrecordhost[]" value="{$dnsrecord.hostname}" size="10" class="form-control" {$OP_blockedns} /></td>
                    <td>
                        <select name="dnsrecordtype[]" class="form-control" {$OP_blockedns}>
						<option value="A"{if $dnsrecord.type eq "A"} selected="selected"{/if}>A</option>
						<option value="AAAA"{if $dnsrecord.type eq "AAAA"} selected="selected"{/if}>AAAA</option>
						<option value="CAA"{if $dnsrecord.type eq "CAA"} selected="selected"{/if}>CAA</option>
						<option value="CNAME"{if $dnsrecord.type eq "CNAME"} selected="selected"{/if}>CNAME (Alias)</option>
						<option value="MX"{if $dnsrecord.type eq "MX"} selected="selected"{/if}>MX (Mail)</option>
						<option value="NS"{if $dnsrecord.type eq "NS"} selected="selected"{/if}>NS</option>
						<option value="SOA"{if $dnsrecord.type eq "SOA"} selected="selected"{/if}>SOA</option>
						<option value="SPF"{if $dnsrecord.type eq "SPF"} selected="selected"{/if}>SPF</option>
						<option value="SSHFP"{if $dnsrecord.type eq "SSHFP"} selected="selected"{/if}>SSHFP</option>
						<option value="SRV"{if $dnsrecord.type eq "SRV"} selected="selected"{/if}>SRV</option>
						<option value="TLSA"{if $dnsrecord.type eq "TLSA"} selected="selected"{/if}>TLSA</option>
						<option value="TXT"{if $dnsrecord.type eq "TXT"} selected="selected"{/if}>TXT</option>
                        </select>
                    </td>
                    <td><input type="text" name="dnsrecordaddress[]" value="{$dnsrecord.address}" size="40" class="form-control" {$OP_blockedns} /></td>
                    <td>
                        {if $dnsrecord.type eq "MX"}<input type="text" name="dnsrecordpriority[]" value="{$dnsrecord.priority}" size="2" class="form-control" />{else}<input type="hidden" name="dnsrecordpriority[]" value="N/A" />{$LANG.domainregnotavailable}{/if}
                    </td>`

**Comment by soberoctober** [comment]
fixed in d240d8f
