### ISSUE TITLE
Error with contacts

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#9]
The module ignores the options created in whmcs on the domain contacts.

I have since the administrative and technical contact is us and the owner is the customer.
He ignores it, it's all the customer.

Attached is the catch:

https://i.gyazo.com/5abc9ba7b50d9df59ca6e8972ebb6214.png
![0cf523dca95a7d012a0864147e9c7fd7](https://user-images.githubusercontent.com/22803933/40975936-cd927862-68cc-11e8-8605-db26c5e74e91.png)

**Comment by wmetge** [comment]
Thank you for brining this to our attention. It will be solve in the upcoming release of the module

**Comment by wmetge** [comment]
Hi @coriaweb, please note this issue has been fixed with the latest release of the module. Please be in contact with any other issues
