### ISSUE TITLE
[BUG] VAT number cannot be blank during .pt domain registration

### ISSUE THREAD

**Issue by maverick85** [openprovider/OP-WHMCS7#90]
Hi,

When a customer tried to register a .pt domain I got the following error:

`Domain Registration Failed - Domain: ---.pt - Error: Customer additional data parameter value is invalid:<br>`

I got the following message from your support:

> Please see the list of requirements for a .pt registration:
> 
> Successful domain registration requires:
> 
>     domain's contact handles (owner, administrative, etc.)
>     owner handle requires additional data
>         individuals - Tax number
>         company - VAT number
>     two or more nameservers or a nameserver group
> 
> Get acquainted with the name policy while registering name (non-compliant domains are deleted with no refunds)
> 
> Note: ID/VAT must always correspond to the country where the company/person is registered ("X" country VAT cannot be associated with a contact with a "Y" country address, country and VAT must belong to the same country)
> 
> https://support.openprovider.eu/hc/en-us/articles/360000756888--pt

The Extra Fields for .pt domain registration on the OpenPrivider WHMCS module are:
- Company Registration Number
- Social Security Number
- Passport number

None of these corresponds to a VAT/Tax ID, or in the limit maybe company number on the first, but that isn't an individual TAX ID/Vat number is the same in Portugal, and the error message doesn't specify the issue properly.
It would make sense given the requirements for a "VAT/Tax ID" field and maybe an address field given this requirement in particular:

> Note: ID/VAT must always correspond to the country where the company/person is registered ("X" country VAT cannot be associated with a contact with a "Y" country address, country and VAT must belong to the same country)

As the customer's main account isn't from Portugal, but is a portuguese citizen with a portuguese ID and address, and is able to provide the required elements for registration.

Thanks

**Comment by maverick85** [comment]
Follow-up on this issue, I tried to create the client manually on RCP with the full PT details.

I am getting this error bellow, the phone number is correct, using +351 international code and tried several variants of the number all give this error and I can't proceed.

<img width="353" alt="Screenshot 2020-06-06 at 15 25 14" src="https://user-images.githubusercontent.com/10200278/83946630-fd88e280-a809-11ea-9584-fddbea21dc68.png">

**Comment by soberoctober** [comment]
hi @maverick85 

>Also I noticed on RCP there's no field for an individual VAT/TaxID. People have VAT/TaxID's which is different from social security or passport.

The VAT field will appear in RCP UI when you type in the Company name.
![Screenshot 2020-06-08 at 12 12 01](https://user-images.githubusercontent.com/19632372/84020180-9a838100-a9ac-11ea-89d1-d62fcbae2ccd.png)


I tried creating a company contact handle with some arbitrary data (including phone number and address of Lisbon City Hall) and it went as expected:
![Screenshot 2020-06-08 at 12 12 20](https://user-images.githubusercontent.com/19632372/83994786-9d1cb100-a981-11ea-943b-998585cda096.png)

Could you double check the phone format?

As for the additional fields for .pt in the module, we will review them and make the necessary adjustments asap.

**Comment by maverick85** [comment]
Hi @soberoctober thank you for your reply.

About the VAT/TaxID:
One doesn't need to be a Company to have a VAT number/TaxID (is the same here).

I, myself, as a Portuguese individual, have a VAT/TaxID.
My customer, who has a company in the UK but is a Portuguese citizen, has a VAT/TaxID, but no Company Name to provide as the company is from UK not PT and has nothing to do with the customers own VAT/TaxID.

So I can't fill the "Company name" as there is no company name, there are only individuals.

About the contact, I will be in the office in the next 30 minutes and I will retry to create the contact and I'll post here in the next hour with the results.

**Comment by soberoctober** [comment]
@maverick85 the issue was caused by incorrect mapping of the additional fields in the createCustomerRequest.

Please either update to this commit 82bc127 or change 

`"op_location" => "customerExtensionAdditionalData"` to `"op_location" => "customerAdditionalData"` 

in 

`/whmcs/modules/registrars/openprovider/configuration/additionalfields.php` for .PT-related arrays `$additionaldomainfields[".pt"]`.

**Comment by maverick85** [comment]
Hi @soberoctober 

I have proceeded with this solution:

> @maverick85 the issue was caused by incorrect mapping of the additional fields in the createCustomerRequest.
> 
> Please either update to this commit [82bc127](https://github.com/openprovider/OP-WHMCS7/commit/82bc1274f304fae3d5f9255b254311a58fe58e2d) or change
> 
> `"op_location" => "customerExtensionAdditionalData"` to `"op_location" => "customerAdditionalData"`
> 
> in
> 
> `/whmcs/modules/registrars/openprovider/configuration/additionalfields.php` for .PT-related arrays `$additionaldomainfields[".pt"]`.

![Screenshot 2020-06-08 at 12 09 27](https://user-images.githubusercontent.com/10200278/84023971-f2a48e00-a980-11ea-946c-ce3b2822f49f.png)

However, I have filled the VAT number on the following fields:

Customer > Profile > VAT Number
Customer > Domains > "domain.pt pending registration" > Company Registration Number

I have filled the VAT number on both these fields. Error above.

I don't think the main profile VAT number should be used anyways, as the customer's main address isn't Portuguese.
Again I strongly believe the .pt registration should have specific fields:

Checkbox with "Individual" or "Company"
Individual:
- NIF (VAT/TaxID for individuals)
- Address for individuals (or just submit country = Portugal)

- NIPC (same as NIF /VAT/TaxID for companies)
- Company Address (Country has to be Portugal)

I am sending a screenshot of the registration space at the .pt main registrar association.
As you can see it asks for the NIF and Country. There is no requirement for company numbers, passport numbers, social security numbers, none of which match.

![Screenshot 2020-06-08 at 12 15 27](https://user-images.githubusercontent.com/10200278/84026062-86c42480-a984-11ea-8405-139f16c90421.png)

**Comment by soberoctober** [comment]
hi @maverick85 

> However, I have filled the VAT number on the following fields:
> Customer > Profile > VAT Number
> Customer > Domains > "domain.pt pending registration" > Company Registration Number
> I have filled the VAT number on both these fields. Error above.

Unfortunately, this won't work because of the issue #91. It's been around for some time, but we'll cover it in the scope of version 3.4. As of right now, the fields will only be propagated to the API during domain registration/transfer from the _Client area_.

As for the .pt specific requirements. When you're registering a domain as an individual via the Client Area, the Social Security Number is mapped to <socialSecurityNumber> field of the <additionalData> node of createCustomerRequest API call. Which in turn is provided as a Fiscal number to DNS PT registry in the form of a <ptcontact:vat> extension.

So, speaking in the registry's terms, Social Security Number would directly correspond to NIF.

We could make an addendum to the "Name" in the configuration file to mark it as such. Or you could that on your personal installation by overwriting .PT fields in `resources/domains/additionalfields.php`.

**Comment by maverick85** [comment]
> As for the .pt specific requirements. When you're registering a domain as an individual via the Client Area, the Social Security Number is mapped to field of the node of createCustomerRequest API call. Which in turn is provided as a Fiscal number to DNS PT registry in the form of a ptcontact:vat extension.

> So, speaking in the registry's terms, Social Security Number would directly correspond to NIF.

I don't understand this.
1. the social security number and the VAT/TaxID are two totally different things.
The Social Security number is completely separated from VAT/NIF and has 11 digits.
The VAT number has 9 digits.

2. The RCP has the following fields:
 - VAT Number (only appears under the fold after filling company name)
 - Passport/ID number
 - Social Security Number

VAT is VAT, TAX or NIF.
What I get from your comment is that the info on "social security number" goes to .pt VAT.

Why?
Why not to map the additional domain fields to the VAT field on RCP, and why not submit VAT as NIF, which it is, instead of using social security which is something completely different?

Would it be so hard to map the correct fields?
Should I change my "additionalfields.php" knowing its just a quick-fix not a real long-lasting solution?

![Screenshot 2020-06-09 at 11 44 41](https://user-images.githubusercontent.com/10200278/84138981-05819600-aa47-11ea-85c3-5eedc9888d6a.png)

![Screenshot 2020-06-09 at 11 44 22](https://user-images.githubusercontent.com/10200278/84139002-09adb380-aa47-11ea-91db-4e55a94126c5.png)

**Comment by soberoctober** [comment]
@maverick85 since VAT is neither a part of Customer additional data nor Extension additional data, it has to provided as a [Custom Client Field](https://docs.whmcs.com/Custom_Fields#Client_Custom_Fields) and nested right after command name node of the request:

```
<createCustomerRequest>
    <companyName>Hosting Unlimited</companyName>
    <vat></vat>
    <name>
      <initials>J.B.</initials>
      <firstName>John</firstName>
      <prefix>van</prefix>
      <lastName>Halen</lastName>
    </name>
```

Currently we don't have a quick solution for this. The workaround would be to:

- take the contact handle of the WHMCS client which was created during last registration attempt (the actual handle ID can be taken from the Utilities > Module Logs > createcustomerrequest)
- modify it in RCP to add a vat number (and other important data)
- retry domain registration with that same sub-account, it will be reused unless something in WHMCS object

**Comment by maverick85** [comment]
Hi @soberoctober thank you for your reply.

Not sure if I understood you entirely but:
- VAT number is not supplied by the WHMCS API that's what you mean, right?
- Why is it not possible to add something to `resources/domains/additionalfields.php` like:

```
// .pt
$additionaldomainfields[".pt"][] = array(
    "Name" => "VAT Number",
    "LangVar" => "ptVatNumber",
    "Type" => "text",
    "Size" => "30", // correct would be 9 numbers
    "op_location" => "customerAdditionalData",
    "op_name"  => "vatNumber"
);
```
I mean, the VAT field exists on RCP. I am not completely understanding why isn't it possible to add a field that maps to RCP's VAT field and submit that on the request? Is that what you mean by "is neither part of customer additional data nor..." but why can't you make it part, if this VAT number is right there on RCP?
You made a field to Company Registration Number, that fills the field "Company Registration Number" on RCP, a field called "Passport ID" that fills the same info, etc. correct?

So how hard does it become to map a new field to an existing field on RCP?

**Comment by soberoctober** [comment]
@maverick85 

>VAT number is not supplied by the WHMCS API that's what you mean, right?

Not quite.

I've been looking at the codebase and it seems like there is a suitable solution.

First of all you have to create a Custom Client Filed for VAT in WHMCS which I mentioned earlier.

Navigate to **Setup > Custom Client Fields** and create a `VATNumber|VAT Number` text field.
Make sure it appears in the admin area on the Client Profile page. Add a valid VAT of your client to their profile.

Then uncomment the following line in `/whmcs/modules/registrars/openprovider/OpenProvider/API/Customer.php` to the `// set values` block of the `__construct` method:

```
$this->vat  =  CustomField::getValueFromCustomFields('VATNumber', $params['customfields']);
```

This will allow providing the data from that custom field to a `<vat>` field of the createDomainRequest API call.

>Why is it not possible to add something to resources/domains/additionalfields.php like

Those fields serve a different purpose. They modify either `<additionalData>` or `<extensionAdditionalData>` sections of the createDomainRequest call. These are separate entities that correspond to various(non-standard) regulations of domain registries.

**Comment by maverick85** [comment]
Hi @soberoctober 
I'm very sorry I was away the last few days. I will come back at this today and give you feedback on it.

**Comment by maverick85** [comment]
@soberoctober 
I have made de changes according to your instructions.

As soon as I get a registration that hits these requirements I'll provide feedback.

**Comment by soberoctober** [comment]
@maverick85 I have described the aforementioned w/a in [this KB article](https://support.openprovider.eu/hc/en-us/articles/360014361440-How-to-add-a-VAT-customer-field-in-WHMCS).

Please reopen this issue, unless the problem disappears.
