### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sorry4uboth** [openprovider/OP-WHMCS7#93]
in the zip file, in modules/registrar, there should be only one folder named openprovider, however the content of this folder is also outside of openprovider module.

it seems you copied the data twice.

kindly check the zip structure again at version 3.3.1

**Comment by wmetge** [comment]
@sorry4uboth thanks for bringing this to our attention, we will get it fixed for subsequent releases

**Comment by soberoctober** [comment]
d240d8f
