### ISSUE TITLE
Wrong Documentation, Missing files

### ISSUE THREAD

**Issue by sorry4uboth** [openprovider/OP-WHMCS7#95]
Hello,

in here, you reference to a file that does not exists:
https://github.com/openprovider/OP-WHMCS7/blob/master/docs/scheduled_domain_transfer.md

Install the cron: php modules/addons/openprovider/cron/Synchronise.php
The addon will fetch all transfers now.

here again:
https://github.com/openprovider/OP-WHMCS7/releases

Navigate to modules/registrars/openprovider/cron/ on the server where WHMCS is installed
Run php -d max_execution_time=0 DownloadTldPrices.php

this files does not exist too.

also after upgrading, the sync feature does not work anymore and dies.
EDIT: it is very slow now.

**Comment by soberoctober** [comment]
hi @sorry4uboth 

> in here, you reference to a file that does not exists:
> https://github.com/openprovider/OP-WHMCS7/blob/master/docs/scheduled_domain_transfer.md
> 
> Install the cron: php modules/addons/openprovider/cron/Synchronise.php

Are you sure you're in the right directory?
It should be [/modules/addons](https://github.com/openprovider/OP-WHMCS7/tree/master/modules/addons/openprovider/cron) not `/modules/registrars`

As for this:

> Navigate to modules/registrars/openprovider/cron/ on the server where WHMCS is installed
> Run php -d max_execution_time=0 DownloadTldPrices.php

For now, that functionality is only available on a separate branch - 93e86aaf2a889975bcaf31145e0b28963d192d4f
We'll merge it when it's ready for general use. Sorry we didn't mention that fact in the release comments.

**Comment by wmetge** [comment]
@sorry4uboth thank you for your feedback, please see the latest documentation
