### ISSUE TITLE
[FR] Adding "tags" to the profile of reseller customers

### ISSUE THREAD

**Issue by coriaweb** [openprovider/OP-WHMCS7#96]
**Is your feature request related to a problem? Please describe.**
Resellers are angry at the emails their customers receive because they are not personalized and our company name appears.

**Describe the solution you'd like**
We need to be able to select a "label" in the WHMCS customer profiles. We have seen that openprovider has the option of being able to customize emails for customers, but they have to be linked to a label.

A box should appear in the profiles with the tags previously created in openprovider and which can be selected for a customer. This way your emails will be personalized.

**Additional context**
I think that label should be sent along with the api in the call when registering a domain, so that it is added to the client who is registering the domain. Since the reseller can put it in the customer's name directly.

**Comment by coriaweb** [comment]
Hello!

Do you know if this is possible? I have several clients who are interested in the subject of personalized emails with their names and not with ours.

Greetings!

**Comment by wmetge** [comment]
hi @coriaweb this feature is possible, and will be included in the next release, before the end of the month. We will be interested in receiving your feedback.

**Comment by coriaweb** [comment]
> hi @coriaweb this feature is possible, and will be included in the next release, before the end of the month. We will be interested in receiving your feedback.

Super interesting this. Looking forward to seeing it.

Thank you!

**Comment by wmetge** [comment]
@coriaweb thank you for your patience please see the latest commit to master branch, which includes this feature request. An explanation on how to assign tags to your customers can be [found here](https://github.com/openprovider/OP-WHMCS7/blob/master/docs/associate_tags_with_customers.md)
